### ISSUE TITLE
[Installer] gitea for Windows

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#101]
I forgot to add the `install.ps1` for Windows for this.

This will be very similar to `caddy`. See https://github.com/webinstall/webi-installers/issues/93, https://github.com/webinstall/webi-installers/pull/106.

**Comment by meanmachin3** [comment]
I'll take this one

**Comment by coolaj86** [comment]
This will actually be more similar to `arc`.

- `arc` releases: https://github.com/mholt/archiver/releases/tag/v3.5.0
- `gitea` releases: https://github.com/go-gitea/gitea/releases/tag/v1.14.6

https://github.com/webinstall/webi-installers/blob/main/arc/install.ps1

**Comment by coolaj86** [comment]
I've got a PR for this, so closing.
