### ISSUE TITLE
[Installer] Add shfmt

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#105]
# Add `shfmt`

We want to add `shfmt` because...

- [Prettier](https://webinstall.dev/prettier) doesn't handle bash scripts
- `shfmt` does
    - also uses some existing style guidelines well (i.e. Google's bash guidelines)

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

# Special note

`shfmt` is a "bare naked" release, so it follows the special `mv` rule mentioned in the `.sh` and `.ps1` comments and in the video.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/mvdan/sh/releases>
   ```bash
   rsync -av _example/ shfmt/
   ```
   - [ ] update `shfmt/release.js` to use the official repo
   - [ ] `shfmt` is a bare-naked release, so it follows the **special `mv` rule** mentioned in the tutorial video
      - see `jq`, `gitea`, and `comrak` as examples of this
   - [ ] find and replace to change the name
     - [ ] update `shfmt/install.sh` (see `jq` as examples)
     - [ ] update `shfmt/install.ps1` (see `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `shfmt/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

# Note to self (related)

Should be able to use this with vim-autofmt:
- https://vimawesome.com/plugin/vim-autoformat

**Comment by anuragsati** [comment]
Hello! I'm new here. I would like to work on this.

**Comment by coolaj86** [comment]
Awesome. Do it!

**Comment by adithyasunil26** [comment]
@coolaj86 Please take a look at my PR (#174).

**Comment by coolaj86** [comment]
this was merged a while back, closing
