### ISSUE TITLE
Remove debug `dir` output from scripts

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#107]
# What's wrong?

In one of the early examples I used `& dir` for debugging purposes.

By accident the extra command was copied into many of the PowerShell scripts.

### Example

The change that needs to be made will look like this:

`_example/install.ps1`:

```diff
diff --git a/_example/install.ps1 b/_example/install.ps1
index ad1376e..348c724 100644
--- a/_example/install.ps1
+++ b/_example/install.ps1
@@ -46,7 +46,6 @@ IF (!(Test-Path -Path "$pkg_src_cmd"))
         # Windows BSD-tar handles zip. Imagine that.
         echo "Unpacking $pkg_download"
         & tar xf "$pkg_download"
-        & dir

         # Settle unpacked archive into place
         echo "Install Location: $pkg_src_cmd"
```

It's just a matter of removing the extra `& dir` that does not need to be there.

# Remove the Debug output

1. Clone this repo
2. Find and remove all lines with `& dir` in the `.ps1` files
3. Make a PR

# Example of how to contribute

```bash
# Clone and go into the repo
mkdir -p github.com/webinstall/
pushd github.com/webinstall/
    git clone git@github.com:webinstall/packages.git
    pushd packages/
```

You can use `rg` or `grep` inside the repo to do a quick recursive search and see where all of the files are.

```bash
    rg '& dir'
```

If you don't already have `rg` (ripgrep), but would like to use it:

```bash
    curl -fsS https://webinstall.dev/rg | bash

    PATH="$HOME/.local/bin:$PATH"
```

From that list, just work through the files and remove those lines.

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

# Skills needed

- can do a find & replace
- can git clone and git push

**Comment by anuragsati** [comment]
Hello! I'm new here, can i take this?

**Comment by coolaj86** [comment]
Fixed in https://github.com/webinstall/webi-installers/pull/120
