### ISSUE TITLE
[Installer] Add goreleaser

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#122]
# Add goreleaser

We want to add `goreleaser` because...

- it works consistently across Windows, Mac, and Linux
- it builds cross-platform go programs and releases to Github, Gitea, or Gitlab, etc

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/goreleaser/goreleaser/releases>
   ```bash
   rsync -av _example/ goreleaser/
   ```
   - [ ] update `goreleaser/release.js` to use the official repo
   - [ ] Learn how `goreleaser` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named goreleaser?)
   - [ ] find and replace to change the name
     - [ ] update `goreleaser/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `goreleaser/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `goreleaser/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by coolaj86** [comment]
Some things that should make it into the README.md Cheat Sheet:

```bash
goreleaser init
goreleaser --snapshot --skip-publish --rm-dist
```

**Comment by SenorGrande** [comment]
Hi there, could I take a crack at this please?

**Comment by coolaj86** [comment]
Please do.

If you can put together a decent Cheat sheet for it from my notes above, that would be great too.

**Comment by coolaj86** [comment]
Moved to https://github.com/webinstall/webi-installers/pull/140
