### ISSUE TITLE
[Installer] Add `yq` (for editing YAML configs)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#130]
# Add yq

https://github.com/mikefarah/yq

We want to add `yq` because it can make configuring `config.yml` files (such as `alacritty`s config file) much easier than writing custom code.

It's written in `go`, so it works consistently across Windows, Mac, and Linux.

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/mikefarah/yq/releases>
   ```bash
   rsync -av ./_example/ ./yq/
   ```
   - [ ] update `yq/release.js` to use the official repo
   - [ ] Learn how `yq` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named yq?)
   - [ ] find and replace to change the name
     - [ ] update `yq/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `yq/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `yq/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by coolaj86** [comment]
Things to make sure we have in the README:

(see the yq docs on their homepage)

- how to set an existing value nested in an object
- how to set an existing value nested in an array
- how to create a new value
- how to delete a value

**Comment by proxium** [comment]
@coolaj86 I'll like to take this.

**Comment by coolaj86** [comment]
@proxium Are you still interested in this?

**Comment by adithyasunil26** [comment]
Please check #169
