### ISSUE TITLE
problem with Homebrew installer

### ISSUE THREAD

**Issue by MichaelDMcCracken** [webinstall/webi-installers#141]
Brand new computer. Wouldn't install brew using webi, so I had to use the install command from brew.sh. Worked properly.

If I recall, the error had to do with unable to contact the software update server when installing xcode command line tools.

**Comment by MichaelDMcCracken** [comment]
Brew installer asked for my password, but Webi didn't.

**Comment by coolaj86** [comment]
Ah, yes, if you don't have xcode installed and haven't accepted the license agreement, it can't install brew.

Brew would ask you about these things from the webi installer, I think, but when you `curl | bash` you loose `stdin` to the pipe between `curl` and `bash`, so user input can't be prompted.

https://apple.stackexchange.com/a/213151/27465

**Comment by coolaj86** [comment]
Interestingly, I don't have xcode installed and it works for me.

Perhaps we just need to add this to the brew installer:

```bash
xcode-select --install
```

I'll have to test this on a fresh macOS VM to see if that will work.

**Comment by coolaj86** [comment]
Fixed in https://github.com/webinstall/webi-installers/pull/143, pending review.
