### ISSUE TITLE
problem with My IP installer

### ISSUE THREAD

**Issue by MichaelDMcCracken** [webinstall/webi-installers#142]
Just installed on brand new Macbook. No output on myip command

**Comment by coolaj86** [comment]
Thanks for the report.

ipify just changed their API 3 days ago:

> Oct 1, 2020 the A record for api6.ipify.org will be removed to make the subdomain only for IPv6 requests. For universal access please use api64.ipify.org. - https://www.ipify.org/

Fixed in https://github.com/webinstall/webi-installers/commit/68cb795084086c3a1670e3ca865e5cd4ec1847ef

Hotfix deployed to production.

You can `webi myip` and the new version should work for you. 👍
