### ISSUE TITLE
[Installer] Add ffmpeg

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#148]
# Add ffmpeg

We want to add `ffmpeg` because...

- it's normally ridiculously complicated to install and requires hundreds of dependencies through package management systems... but now we've got https://github.com/eugeneware/ffmpeg-static/releases 

Note: this is a break to the general rule of no 3rd party builds... because in this case the 1st party builds either don't exist, or are terrible.

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

**Notes**:
- The windows binaries seem to be missing the `.exe` suffix. That will need to be accounted for in the releases.js and install.ps1.
- Should be able to get version with `ffmpeg -version | head -n 1 | cut -d' ' -f 3`.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/eugeneware/ffmpeg-static/releases>
   ```bash
   rsync -av _example/ ffmpeg/
   ```
   - [ ] update `ffmpeg/release.js` to use the official repo
   - [ ] Learn how `ffmpeg` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named ffmpeg?)
   - [ ] find and replace to change the name
     - [ ] update `ffmpeg/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `ffmpeg/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `ffmpeg/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by ImagineZero0** [comment]
Hey @coolaj86,
Can I work on this?

**Comment by ryanburnette** [comment]
@ImagineZero0 Go for it!

**Comment by ImagineZero0** [comment]
Hey @ryanburnette,
I am going throught the provided steps but I get an error while running 

`
node releases.js
`

which says that 

node:11775) UnhandledPromiseRejectionWarning: TypeError: gHubResp.forEach is not a function
    at request.then (/home/imaginezero/Desktop/Github/webi-installers/_common/github.js:47:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Can you look at this.?

**Comment by coolaj86** [comment]
You've reached your Github API limit for that IP address. You can create a `.env` with `GITHUB_TOKEN=xxxxxxx` with your own personal github access token, and the limit will go away.

**Comment by coolaj86** [comment]
The other possibility is that you've made a typo in the github owner and project name and so there's an error response rather than a list of releases.

**Comment by MichaelYogar** [comment]
Hi, am I allowed to work on this? I am new to open source!

**Comment by coolaj86** [comment]
@ImagineZero0 any update on this?

**Comment by ImagineZero0** [comment]
Hey @coolaj86, Sorry for the delay, I got caught up in some of my academic work, I will working on it now...

**Comment by stavoxnetworks** [comment]
I will take this issue if you will permit me.

**Comment by coolaj86** [comment]
@stavoxnetworks Go ahead.

**Comment by stavoxnetworks** [comment]
Te ffmpeg repo mentioned above no longer exists. Should I used the install repo ? https://github.com/q3aql/ffmpeg-install

**Comment by coolaj86** [comment]
Maybe I put the wrong link earlier. I believe this is the correct one:

https://github.com/eugeneware/ffmpeg-static/releases

There’s several similar repos. I must have copied from the wrong tab earlier.

**Comment by stavoxnetworks** [comment]
Right on. That one is good. Thank you!

**Comment by stavoxnetworks** [comment]
I am continuing to work on this. The ffmpeg installer seems to be broken due to an issue with install.js so Im stuck there for the moment. I will update you ASAP.

**Comment by coolaj86** [comment]
Don't try to follow any of their node instructions. Just follow the guide using github releases.

**Comment by coolaj86** [comment]
I'm hoping for compressed releases to come soon:
https://github.com/eugeneware/ffmpeg-static/issues/69
