### ISSUE TITLE
[Installer] Add LF(Terminal Based File Manager)

### ISSUE THREAD

**Issue by HARSH-SHETH** [webinstall/webi-installers#149]
# Add LF
We want to add `LF(terminal based file manager)` because...

- It makes managing and navigating files super easy. 
- It is cross platform and is written in GO language.  

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   https://github.com/gokcehan/lf/releases/
   ```bash
   rsync -av _example/ LF/
   ```
   - [ ] update `LF/release.js` to use the official repo
   - [ ] Learn how `LF` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named LF?)
   - [ ] find and replace to change the name
     - [ ] update `LF/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `LF/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `LF/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by coolaj86** [comment]
@HARSH-SHETH please fill out the rest of the CHANGE-MEs.

It looks like https://github.com/jarun/nnn has static Linux builds, which is good, but you’ll have to open an issue about publishing static macOS and Windows builds.

Also, nnn is written is C, which is neither, safe, nor cross-platform, nor safe.

Is there something similar that’s written in a safe language like Go or Rust?

**Comment by HARSH-SHETH** [comment]
I have filled out the CHANGE-MEs and replaced NNN with LF(cross platform and written in GO).

**Comment by coolaj86** [comment]
@HARSH-SHETH Would you be interested in adding this?

**Comment by HARSH-SHETH** [comment]
> @HARSH-SHETH Would you be interested in adding this?

Yes, I am interested in adding this.

Do I have to follow the steps written in the issue ?

**Comment by coolaj86** [comment]
This was added. Closing.
