### ISSUE TITLE
Quieter installs for scripting

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#153]
I'm trying to get webi installs to quiet down for when I use it in provisioning scripts. The install command already has `-sS`, but there are progress bars that pollute my logs. What else can I do to quiet down webi installs?

**Comment by coolaj86** [comment]
I'm pretty sure that has to do with interactive / non-interactive shell mode over ssh.

It's probably `wget` that's making the noise. We may be able to add some sort of option to force it to rewrite the console in-place even in non-interactive mode: https://superuser.com/a/1551463/73857

**Comment by coolaj86** [comment]
Should be fixed in https://github.com/webinstall/webi-installers/commit/36e76120c7f18d15487b48b63677d08c92ea6ac5
