### ISSUE TITLE
[Installer] Add dotenv-linter

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#155]
# Add dotenv-linter

We want to add `dotenv-linter` because it's a nice cross-platform tool to check that a `.env` file is what it should be.

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

Also: We'll want to get this added to <https://dotenv-linter.github.io/#/installation>:

Mac, Linux:

```bash
curl -sS https://webinstall.dev/dotenv-linter | bash
```

Windows 10:

```pwsh
curl.exe -A MS https://webinstall.dev/dotenv-linter | pwsh
```

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/dotenv-linter/dotenv-linter/releases>
   ```bash
   rsync -av _example/ dotenv-linter/
   ```
   - [ ] update `dotenv-linter/release.js` to use the official repo
   - [ ] Learn how `dotenv-linter` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named dotenv-linter)
   - [ ] find and replace to change the name
     - [ ] update `dotenv-linter/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `dotenv-linter/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `dotenv-linter/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by patrick-gu** [comment]
Is it alright if I try this?

**Comment by patrick-gu** [comment]
I added this in #159 if you would like to take a look. Thanks!

**Comment by coolaj86** [comment]
Closing because this was merged. Thanks again. :)
