### ISSUE TITLE
caddy cors

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#160]
This would make a good addition to the Caddy cheat sheet. It's a CORS snippet for Caddy.

https://gist.github.com/ryanburnette/d13575c9ced201e73f8169d3a793c1a3

**Comment by lastlink** [comment]
pull requests are often more helpful for requests for documentation enhancements

**Comment by ryanburnette** [comment]
@lastlink I'm one of the project authors. This is just a note to self to add it at some point the future. I agree, though! :)

**Comment by lastlink** [comment]
Sorry, I just see issues like this all the time, forgot to check.

**Comment by ryanburnette** [comment]
All good :) thank you for keeping an eye out

**Comment by coolaj86** [comment]
It's finally going in! #649 

# Preview

https://next.webinstall.dev/caddy
