### ISSUE TITLE
[Solved] Apple Silicon (M1) Support

### ISSUE THREAD

**Issue by abisuq** [webinstall/webi-installers#162]
## What were you trying to install (or what else went wrong)?

watchexec

## What exactly did you do?

I ran `curl -sS https://webinstall.dev/watchexec | bash` to install  watchexec.

## What went wrong?
```

Thanks for using webi to install 'watchexec' on 'macos/arm64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Error: no 'watchexec' release for 'macos' on 'arm64' as one of 'tar,exe,zip,xz,git,dmg,pkg' by the tag ''
       'watchexec' is available for 'linux,macos,windows' on 'amd64' as one of 'tar,zip'
       (check that the package name and version are correct)

       Double check at https://webinstall.dev/api/releases/watchexec@.tab
```

Actually, it can run automatically through Rosetta 2
 
```
1.14.1	-	stable	2020-09-30	macos	amd64	tar.xz	-	https://github.com/watchexec/watchexec/releases/download/1.14.1/watchexec-1.14.1-x86_64-apple-darwin.tar.xz
```

## Which OS did you try on?

- [x] Mac

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] M1 Macbook (amd64)

**Comment by coolaj86** [comment]
The issue here is

1. Most programs have not updated for M1 chips yet
2. The Webi auto-detection needs an override for the new macs

I'm going to let this sit in the back of my mind today and see if an intelligent solution comes to me.

My guess is that I'm just going to have to force Mac arm64 to behave as Mac amd64. Ultimately I could use some sort of ranking system to prefer arm64 when available... but that feels overly complex.

In the meantime, if you care to take a look at these and try something on your own, feel free:

- test.js
- ua-detect.js
- releases.js

```bash
node _webi/test.js watchexec
```

**Comment by coolaj86** [comment]
@abisuq Can you verify that the `syncthing` installer is working for apple silicon?

```bash
curl -sS https://webinstall.dev | bash
webi syncthing@beta
```

**Comment by abisuq** [comment]
@coolaj86 

```
❯ curl -sS https://webinstall.dev | bash

Thanks for using webi to install 'webi' on 'macos/arm64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Error: no 'pathman' release for 'macos' on 'arm64' as one of 'tar,exe,zip,xz,git,dmg,pkg' by the tag ''
       'pathman' is available for 'linux,macos,windows' on 'amd64,arm64' as one of 'tar,zip'
       (check that the package name and version are correct)

       Double check at https://webinstall.dev/api/releases/pathman@.tab
```

**Comment by coolaj86** [comment]
I just updated `pathman`. Please try again now.

**Comment by abisuq** [comment]
@coolaj86 It works properly.
https://cln.sh/MICMeB

**Comment by coolaj86** [comment]
With `pathman` recompiled, it's fair to say that **Webi supports Apple Silicon**.

However, if you want to run programs that have not yet been updated to for Apple Silicon, your best bet is to have two instances of your Terminal (or iTerm, Alacritty, Kitty, etc) - one which runs with the "Open Using Rosetta" checked for x64 tools.

**Comment by coolaj86** [comment]
# Update: amd64 is now the default fallback

It's no longer necessary to use the x64 emulation trick. amd64 is now the default fallback when macos/arm64 is missing.

https://github.com/webinstall/webi-installers/issues/201
