### ISSUE TITLE
Request for mutagen

### ISSUE THREAD

**Issue by creedasaurus** [webinstall/webi-installers#167]
Didn't know it existed until recently. Pretty nice utility if you sync code to a server for building remotely:

site: https://mutagen.io/
repo: https://github.com/mutagen-io/mutagen

**Comment by coolaj86** [comment]
Sounds good! Will you add it?

**Comment by creedasaurus** [comment]
Yeah!

**Comment by coolaj86** [comment]
@creedasaurus bump
