### ISSUE TITLE
Add pyenv

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#180]
`pyenv` is completely user-installable. It does not require `brew`, as most people assume.

The installer for this would be very much like the installer for Rust. It doesn't use the standard webi boilerplate, it's just a convenience for those who want it.

```bash
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
pathman add ~/.pyenv/bin
```

**Comment by adithyasunil26** [comment]
I have made a PR for this.  #181 
I did not use pathman though. I checked if the user is on zsh or bash and appended the PATH and init statements to the .zshrc or .bashrc files respectively.
