### ISSUE TITLE
Possible Feature Request: a webi config to save for dotfiles repos and the like

### ISSUE THREAD

**Issue by creedasaurus** [webinstall/webi-installers#192]
So maybe this is beyond the simplicity of this project, but I was just thinking about it the other day and it's totally something I've been wanting, but haven't found yet.

So I tend to like to try out new operating systems, or just fiddling with old computers I have lying around and so I tend to like having some of the basics of my configs and programs set up quickly. At one point I was using [Ansible](https://github.com/ansible/ansible) playbooks to set up the programs I usually want on my machine since I could define what I wanted and then run the playbook and it would fetch everything for me. This was a hair bit annoying since it still required setting some stuff up before Ansible was available to run like setting up python and stuff. It also was platform dependent to a point, where it kind of needed certain package managers available to it, like `brew` or `apt` to install everything.

My next attempt, required less of a python dependency: Nix or specifically [Home Manager](https://nixos.wiki/wiki/Home_Manager). Nix seemed like it was a good fit for what I wanted to do for the most part. But the learning curve is crazy and debugging a failed build tends to push me to the limit of time I want to spend _just_ trying to install some stuff. Also, the config language is a little wild and functional. I'll still play with it from time to time, but when something fails, it's crazy to figure out, haha.

So that got me thinking last night: what about a super simple webi-config kind of thing, where webi might be made aware of some ultra basic config/manifest file that a user could create and version into their `dotfiles` repo, allowing you to create a list of the programs (and versions, like the normal API is) in yaml or toml or json or something and then run `webi --config ./path/manifest.json` or even be able to run the curl command against a url that fits the manifest format, and then webi just runs the install command for all those.

You could _maybe_ even do something like `webi --save jq@stable` and it would append it to the manifest or something.

Anyway, I'd love to hear what you think. Obviously one could just version themselves a little script that would just run webi multiple times to get those packages yourself. But it just feels like something that would be cool to have supported and a really clean way of doing it. Not to mention its sort of the thing that brew and apt dont support.

**Comment by coolaj86** [comment]
I want to keep webi itself very light, but here's what I think we might be able to do:

In the case of `webi --XXXXX`, we could check to see if `webi-XXXXX` is available as in <https://webinstall.dev/webi-XXXXX>.

Then whatever comes _after_ `--XXXXX` could be passed as an argument to `webi-XXXXXX foo`.

Is that something you think you could manage?

**Comment by creedasaurus** [comment]
Oh interesting, I think that may work. Do you mind elaborating on this idea a little? 
I guess I'm just wondering -- would this be a separate script in the `webi-installers` repo or would you rather it be a separate project that the `web-XXXX` path would direct to?

**Comment by coolaj86** [comment]
It should go in the same repo.

You can do some sort of bash switch case magic to capture everything that starts with `--`. I don't recall exactly, but it looks something like this:

```
for arg in $@
switch $arg
    (case -h|--help;;
       echo "webi [program[@version]]"
       exit 0
    (case --*;;
        curl -fsSL https://webinstall.dev/webi-${arg#^--:}
end
```

Again, I don't recall the syntax off the top of my head, so that's completely made up, but you'll be able to figure it out by looking at bash docs.

It would go in https://github.com/webinstall/webi-installers/blob/master/_webi/bootstrap.sh (which is escaped because it's a string that's put into a file before running to update webi on each use).

**Comment by creedasaurus** [comment]
Ahaaa. Kk. That makes sense. Well, not sure I'll build something right away for this, but I've got it on the mind. Not sure if you prefer to archive issues if they aren't actively being worked on or anything, but I'm good with whatever.
