### ISSUE TITLE
Request for awless

### ISSUE THREAD

**Issue by thealanberman** [webinstall/webi-installers#193]
https://github.com/wallix/awless

**Comment by ryanburnette** [comment]
@thealanberman Take a look at #194. This is a working installer for awless, but it lacks the cheat sheet that we like to create for our installers. If you create the cheat sheet, we'll merge it into master. I'll give you editing rights on my repo at https://github.com/ryanburnette/webi-installers.

**Comment by ryanburnette** [comment]
@thealanberman Here's where you set up the cheat sheet. Take a look at some of the others for inspiration. https://github.com/ryanburnette/webi-installers/tree/master/awless

**Comment by coolaj86** [comment]
Hey @thealanberman, `awless` has been merged in, but could you do a PR to add a Cheat Sheet section?

**Comment by thealanberman** [comment]
yep, sorry, will try to write this up tonight. :)

- Al

**Comment by coolaj86** [comment]
bump :)

**Comment by coolaj86** [comment]
It's live: https://webinstall.dev/awless (and on the homepage https://webinstall.dev)

@thealanberman One last thing: will you make a PR to the awless repo and update the install instructions to include webi?

**macOS, Linux**:

```bash
curl -sS https://webinstall.dev/awless | bash
```

**Windows**:

```pwsh
curl.exe -A MS https://webinstall.dev/awless | powershell
```

Or

```bash
webi awless
```

**Comment by thealanberman** [comment]
done! (though had to change it a bit to meet the existing format they use
in their readme) https://github.com/wallix/awless/pull/294

- Al

**Comment by coolaj86** [comment]
💯
