### ISSUE TITLE
Request for kind 

### ISSUE THREAD

**Issue by snowbldr** [webinstall/webi-installers#196]
https://kind.sigs.k8s.io/

kind is a tool for running local Kubernetes clusters using Docker container “nodes”.
kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.

**Comment by coolaj86** [comment]
@narcolepticsnowman @adithyasunil26 Please test https://beta.webinstall.dev/kind

I'd love it if you could help put together a more complete Cheat Sheet, @narcolepticsnowman. :)

**Comment by coolaj86** [comment]
@snowbldr Would you mind filling out the Cheat Sheet for `kind`?

Just click edit its README, and add the goodies that are the most useful for you (and that you think will be the most useful to others):
https://github.com/webinstall/webi-installers/blob/add-kind/kind/README.md

A TL;DR sort of thing would be great. :)

**Comment by coolaj86** [comment]
P.S. Here's are what good cheat sheets look like:
- https://webinstall.dev/node/
- https://webinstall.dev/rg/

**Comment by snowbldr** [comment]
Thanks for the reminder, and sorry for the delay. I hope those additions are sufficient.
