### ISSUE TITLE
Typo Fix: Change "DroidSansMono Nerd Font" to "DroidSansMono NF" in Windows docs

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#203]
Just need a small change to these docs: https://github.com/webinstall/webi-installers/blob/master/nerdfont/README.md

```diff
{
  "profiles": {
    "defaults": {
-      "fontFace": "DroidSansMono Nerd Font"
+     "fontFace": "DroidSansMono NF"
    }
  }
}
```

I'd have done this myself... but I can't approve my own PRs, but I can approve _yours_! :D

**Comment by iamayushdas** [comment]
DONE! #204
