### ISSUE TITLE
String Replace: change all occurrences of webi.ps1 with webi-pwsh.ps1

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#205]
# Simple String Replace
we need to do a string replace throughout the entire repository - all scripts, docs, etc - to use `webi-pwsh.ps1` instead of `webi.ps1`.

This would be done pretty easily with [rg](https://webinstall.dev/rg) and [sd](https://webinstall.dev/sd) (or Unix sed, or a similar GUI tool).

## Rational

The reason is that Windows treats both .ps1 and .bat files in PATH as executable for search, but won’t actually run ps1 files - yet ps1 takes precedence in PowerShell.

By renaming the files we can get `webi` to correctly reference `webi.bat`, this saving some keystrokes and eliminating some confusion.

**Comment by jcarterbohan** [comment]
I'll do it

**Comment by coolaj86** [comment]
https://github.com/webinstall/webi-installers/pull/206/commits/7a5d0527cb93ba58efbadeea95080f824feb827d
