### ISSUE TITLE
[Installer] Add vim-shfmt

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#209]
# Add vim-shfmt

We already have [`shfmt`](https://webinstall.dev/shfmt), but that's only half of the job. Now we need to get [`vim-shfmt`](https://github.com/z0mbix/vim-shfmt) (<https://github.com/z0mbix/vim-shfmt>) to finish the job.

This will be similar to our `vim-prettier` and `vim-nerdtree` installers. This should also be included in `vim-essentials`.

```bash
git clone --depth=1 https://github.com/z0mbix/vim-shfmt.git ~/.vim/pack/plugins/start/shfmt
```

```bash
~/.vim/plugins/shfmt.vim
```

```vim
let g:shfmt_extra_args = '-i 4 -sr -ci -s'
let g:shfmt_fmt_on_save = 1

augroup LocalShell
    autocmd!

    autocmd BufWritePre *.sh,*.bash Shfmt
augroup END
```

**Note**: This will **NOT** use the normal `./_example/`, because vim plugins install differently than system tools.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/___CHANGE/ME___/releases>
   ```bash
   rsync -av _example/ CHANGE-ME/
   ```
   - [ ] update `CHANGE-ME/release.js` to use the official repo
   - [ ] Learn how `CHANGE-ME` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named CHANGE-ME?)
   - [ ] find and replace to change the name
     - [ ] update `CHANGE-ME/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `CHANGE-ME/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `CHANGE-ME/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by krylowicz** [comment]
I'll take this.

**Comment by coolaj86** [comment]
https://github.com/webinstall/webi-installers/pull/206/commits/d1fc251c5c5b58c0c81a499ebc9e56c96847478d
