### ISSUE TITLE
[Installer] Add shell-check

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#211]
# Add shellcheck

`shellcheck` is written in Haskell and available for Windows, Mac, and Linux. It does an amazing job at catching rookie mistakes (and old-habits-die-hard mistakes) in `bash`.

https://github.com/koalaman/shellcheck

Adding this will be about as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

For the case of Windows the releases.js will need to be updated to manually tag non-linux, non-darwin zip releases as Windows x64, but tag me and I can jump in to help with that.

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/___CHANGE/ME___/releases>
   ```bash
   rsync -av _example/ CHANGE-ME/
   ```
   - [ ] update `CHANGE-ME/release.js` to use the official repo
   - [ ] Learn how `CHANGE-ME` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named CHANGE-ME?)
   - [ ] find and replace to change the name
     - [ ] update `CHANGE-ME/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `CHANGE-ME/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `CHANGE-ME/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by iamayushdas** [comment]
Assign this to me

**Comment by coolaj86** [comment]
@iamayushdas Take it.

**Comment by coolaj86** [comment]
@iamayushdas Status update? I'm going to unassign you unless I hear back. This has become a higher priority.

**Comment by Ingi-Hong** [comment]
Hi, I'd like to tackle this. If I need help what should I do?

**Comment by coolaj86** [comment]
@Ingi-Hong Take it. Reach out to me. You can comment here, or I'm coolaj86#9759 on Discord.

**Comment by Ingi-Hong** [comment]
I sent a friend request on discord

Also, I'm getting an error whenever I try to test my install.sh: 
```
Found /home/usr/Downloads/shellcheck-v0.7.1.linux.x86_64.tar.xz
Extracting /home/usr/Downloads/shellcheck-v0.7.1.linux.x86_64.tar.xz
Installing to /home/usr/.local/opt/shellcheck-v0.7.1/bin/shellcheck
install-shellcheck.sh: line 215: /home/usr/.local/bin/webi: No such file or directory
```

![Screenshot from 2021-03-30 15-26-31](https://user-images.githubusercontent.com/73002018/113045127-73c94d80-916c-11eb-8505-1605a51b664b.png)

That's the created test file ^^
I'm not sure where the issue originates. Perhaps I'm not treating the file correctly in the template. I'm pretty sure the package unpacks as ./shellcheck-v0.7.1/shellcheck, so I have 

` mv ./shellcheck-*/shellcheck "$pkg_src_cmd"`

in my install.sh.

 Let me know if you need any other info!

**Comment by Ingi-Hong** [comment]
Update: 

1. I installed pathman to get around the issue of line 215. I'm not sure if I was supposed to do that before testing. 

2. shellcheck is installing as a folder in .local/bin. Is it supposed to do that?  

![Screenshot from 2021-03-31 14-37-13](https://user-images.githubusercontent.com/73002018/113193995-9b80ea00-922e-11eb-9393-09a45aed6c23.png)

3. I'm getting success when I test 
```Saved as /home/ingihong/Downloads/shellcheck-v0.7.1.linux.x86_64.tar.xz
Extracting /home/ingihong/Downloads/shellcheck-v0.7.1.linux.x86_64.tar.xz
Installing to /home/ingihong/.local/opt/shellcheck-v0.7.1/bin/shellcheck
Installed 'shellcheck' v0.7.1 as /home/ingihong/.local/bin/shellcheck
```

but shellcheck --version doesn't return anything.

**Comment by coolaj86** [comment]
Open up a PR with a `WIP: ` prefix so I can see what you're doing.

**Comment by coolaj86** [comment]
I'll want to put this in the cheat sheet:
https://gist.github.com/nicerobot/53cee11ee0abbdc997661e65b348f375
