### ISSUE TITLE
[easy] Cleanup ps1 files with minor text change (does not require understanding ps1)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#217]
Basically this is two steps:

1. Every instance of `New-Item` that is nested in an `IF ... Test-Path` should be de-nested - the `IF` is redundant
    ```diff
    -if (!(Test-Path -Path Downloads))
    -{
    -     New-Item -Path Downloads -ItemType Directory -Force
    + New-Item -Path Downloads -ItemType Directory -Force
    -}
    ```
2. Every instance of `New-Item` and `Remove-Item` should be updated to end in `| out-null`
    ```diff
    -Remove-Item -Path "$pkg_dst_cmd" -Recurse -ErrorAction Ignore
    +Remove-Item -Path "$pkg_dst_cmd" -Recurse -ErrorAction Ignore | out-null
    - New-Item -Path Downloads -ItemType Directory -Force
    +New-Item -Path Downloads -ItemType Directory -Force | out-null
    ```

# Tips

You can of course use your familiar GUI tools, but...

If you want to get a quick list of all of the `install.ps1` files throughout the repo using modern CLI tools, you could use `fd` and `rg`, like so:

```bash
curl -sS https://webinstall.dev | bash
webi fd rg

git clone YOUR-FORK
pushd YOUR-FORK
git checkout -b ps1-cleanup
fd | rg 'install\.ps1'
```

You could then edit the files with your weapon of choice. I'd probably use [`sd`](https://webinstall.dev/sd). You could use VS Code or vim or whatever suits your fancy.

# Documentation

If you want to learn some git, try this:
https://www.youtube.com/playlist?list=PLxki0D-ilnqbXhctTFCDGH3fSN7l7ATkL

If you want to see how new projects are added to Webi, see this:
https://github.com/webinstall/webi-installers/blob/master/.github/ISSUE_TEMPLATE/new_installer.md

**Comment by ishanpan** [comment]
I would like to work on this. @coolaj86

**Comment by coolaj86** [comment]
Just for reference, here's what I did to further clean things up:

```bash
sd 'New-Item(.*) Directory -Force' 'New-Item$1 Directory -Force | out-null' */*.ps1
sd 'New-Item(.*) out-null \| out-null' 'New-Item$1 out-null' */*.ps1
```
