### ISSUE TITLE
installing homebrew on linux

### ISSUE THREAD

**Issue by makuzaverite** [webinstall/webi-installers#227]
I'm trying to install homebrew on Linux ubuntu 20.04 running inside wsl but the installation fails 

## What went wrong?

![image](https://user-images.githubusercontent.com/53856673/115566579-a58c8a80-a2ba-11eb-9480-8389c6ce1f9f.png)

## Which OS did you try on?

- [ ] Mac
- [x] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Thanks for the report.

I'll have to add a check for Linux and gcc rather than assuming that `brew` is for Mac only. I knew that it could work on Linux, but I didn't know there was much of a market for that.

Curious: Why use brew on Linux? What are you intending to install with brew?

**Comment by makuzaverite** [comment]
They are packages that i really on which requires me to have it like github cli

**Comment by coolaj86** [comment]
This should be fixed now as of https://github.com/webinstall/webi-installers/commit/aa61db993471a5ec35fadbc050126735b9fc200a. Will you try again?

Also, it looks like `gh` (GitHub CLI) is something we could added to Webi: https://github.com/cli/cli/releases/tag/v1.9.2

What other tools do you install via brew? What's the list?

**Comment by coolaj86** [comment]
I'm going to close this out, but I'd still like to know your list.

**Comment by makuzaverite** [comment]
Still not able to install brew the command shows nothing

**Comment by coolaj86** [comment]
Can you be more specific?

I just ran `webi brew` on two different Ubuntu Linux VPSes and, after 400 mb of download 🤮, it installed and when I run `brew --help` I see the brew help.

Sometimes you have to logout and log back in (or re-open your terminal) for the settings to take effect.
