### ISSUE TITLE
[Cheat Sheet] Add `gh` GitHub CLI

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#230]
# Update: Just need the Cheat Sheet

The installer has been done. Now we just need someone to fill out the cheat sheet:

Just edit this README, and add the goodies that are the most useful for you (and that you think will be the most useful to others): https://github.com/webinstall/webi-installers/blob/add-gh/gh/README.md

A TL;DR sort of thing would be great. :)

P.S. Here's are what good cheat sheets look like:
- https://webinstall.dev/node/
- https://webinstall.dev/rg/

# Add GitHub CLI

We want to add `gh` because it's popular and shouldn't require installing 400mb of `brew` to get.

This should be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

Here are the releases:
https://github.com/cli/cli/releases/tag/v1.9.2

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/___CHANGE/ME___/releases>
   ```bash
   rsync -av _example/ CHANGE-ME/
   ```
   - [ ] update `CHANGE-ME/release.js` to use the official repo
   - [ ] Learn how `CHANGE-ME` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named CHANGE-ME?)
   - [ ] find and replace to change the name
     - [ ] update `CHANGE-ME/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `CHANGE-ME/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `CHANGE-ME/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

**Comment by onwuvic** [comment]
@coolaj86 can I pick this up?

**Comment by coolaj86** [comment]
@onwuvic Do it!

**Comment by coolaj86** [comment]
@onwuvic Update?

**Comment by onwuvic** [comment]
@coolaj86 I have gone halfway. I'm just currently tied up at work. I hope to complete it before or during this weekend. Hope that is okay?

**Comment by onwuvic** [comment]
@coolaj86 I will get it done by Friday.

**Comment by onwuvic** [comment]
@coolaj86 I am having issues with the installation each time I run this `bash install-gh.sh` I get this `install-gh.sh: line 225: /Users/victoronwuzor/.local/bin/webi: No such file or directory`. Here are the screenshots. 

I have watched the video and try changing this `mv ./gh-*/bin "$pkg_src_cmd"` and this `Move-Item -Path ".\gh-*\bin\gh.exe" -Destination "$pkg_src_bin"` but the same thing still occurs. What do you think I am missing?
<img width="369" alt="Screenshot 2021-05-10 at 06 27 30" src="https://user-images.githubusercontent.com/17351527/117611322-2e307500-b15b-11eb-82d9-85557346333a.png">
<img width="666" alt="Screenshot 2021-05-10 at 06 28 53" src="https://user-images.githubusercontent.com/17351527/117611330-312b6580-b15b-11eb-8ee6-77b07acdb0e2.png">

**Comment by onwuvic** [comment]
I also have a WIP Pull Request up https://github.com/webinstall/webi-installers/pull/237

**Comment by Tiparium** [comment]
@onwuvic Did you happen to ever solve the `install-gh.sh: line 225: /Users/victoronwuzor/.local/bin/webi: No such file or directory` issue? I'm trying to get zola working and I'm having the exact same problem down to the same line number.

**Comment by onwuvic** [comment]
@Tiparium  No, I was not able to solve it.

**Comment by coolaj86** [comment]
@Tiparium @onwuvic Do you have `webi` installed? https://webinstall.dev

**Comment by coolaj86** [comment]
Oh, I think I see what's happening. The `No such file or directory` is coming from the `install-gh.sh`, which means that on that line you are referencing a file that doesn't exist, or has the wrong name.

You need to double check the contents of `tar xvf gh_1.9.2_macOS_amd64.tar.gz` and make sure that the name you're trying to use actually matches the name of the extracted file.

**Comment by onwuvic** [comment]
@Tiparium Have you been able to fix it? I did mine by first installing webi [https://webinstall.dev](https://webinstall.dev) then I changed this `mv ./gh-*/bin/gh  "$pkg_src_cmd"` to `mv ./"$pkg_cmd_name"*/bin/gh "$pkg_src_cmd"` on `install-gh.sh` file.

**Comment by Tiparium** [comment]
> @Tiparium @onwuvic ~Do you have `webi` installed? https://webinstall.dev~
> 
> **Update**:
> 
> Oh, I think I see what's happening. The `No such file or directory` is coming from the `install-gh.sh`, which means that on that line you are referencing a file that doesn't exist, or has the wrong name.
> 
> You need to double check the contents of `tar xvf gh_1.9.2_macOS_amd64.tar.gz` and make sure that the name you're trying to use actually matches the name of the extracted file.

Installing webi got my `install-zola.sh` working without making any code changes. Still working on the `install.ps1`, which is currently getting as far as creating the correct file structure in `[user]/.local/opt/zola-v0.13.0/bin`, but the actual executable is nowhere to be found. I'm still trying to fix this.
