### ISSUE TITLE
Addition of `webi hugo@vX.Y.Z`

### ISSUE THREAD

**Issue by fu-sen** [webinstall/webi-installers#240]
Hugo themes often don't support the latest version, so you may want to fix the Hugo version.
`webi` seems to be able to do that:
```
webi hugo@v0.83.1
```

But there is no mention of this:
<https://webinstall.dev/hugo/>
<https://github.com/webinstall/webi-installers/tree/main/hugo>

I've seen requests around here in some web services, so I'm sure some people are asking for this.

**Comment by coolaj86** [comment]
I've added this to the docs in one of the current PRs, actually. Closing because I'll merge that tonight.
