### ISSUE TITLE
Add Windows to Hugo

### ISSUE THREAD

**Issue by fu-sen** [webinstall/webi-installers#241]
<https://webinstall.dev/hugo/>
<https://github.com/webinstall/webi-installers/tree/main/hugo>

Why is there no Windows here? 
I use [Scoop](https://scoop.sh/) for a local build on Windows,
Some people would like to install using webinstall.dev or webi.

**Comment by fu-sen** [comment]
I found this. It had no installation script created:
https://github.com/webinstall/webi-installers/pull/24

This can be maintained as a TODO.
The Windows version of `hugo` is also a standalone executable like` caddy`.

**Comment by coolaj86** [comment]
Sorry, just now seeing this. The notification must have gotten lost in my email.

What would have been great is if you had copied the caddy/install.ps1 and then made a PR with hugo/install.ps1.

Would you like to do that and test it?

**Comment by coolaj86** [comment]
Actually, I just made a PR: https://github.com/webinstall/webi-installers/issues/241

Can you test https://beta.webinstall.dev/hugo on a Windows box for me?

**Comment by fu-sen** [comment]
I was just in front of my Windows PC. 

> Can you test https://beta.webinstall.dev/hugo on a Windows box for me?

It's working! The Hugo executable is so simple that it worked as expected.
