### ISSUE TITLE
[Bug] K9s install does not pull the correct release.

### ISSUE THREAD

**Issue by derailed** [webinstall/webi-installers#244]
## What were you trying to install (or what else went wrong)?

k9s

## What exactly did you do?

`curl https://webinstall.dev/k9s | bash` 

## What went wrong?

It says it install the latest revision but does not really. ie installer claim v0.24.9 is installed but in reality v0.23.7 is installed.

NOTE: I didn't contribute the original installer but need to understand what needs to happen to fix this issue. Thank you!!

## Which OS did you try on?

- [x ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
It seems to be installing the correct version to me:

- https://webinstall.dev/api/releases/k9s@.tab?os=macos&arch=amd64&pretty=true
- https://webinstall.dev/api/releases/k9s@.tab?os=linux&arch=amd64&pretty=true

```bash
webi k9s
```

```txt
Thanks for using webi to install 'k9s' on 'linux/amd64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Downloading k9s from
https://github.com/derailed/k9s/releases/download/v0.24.10/k9s_v0.24.10_Linux_x86_64.tar.gz

Saved as /home/app/Downloads/k9s_v0.24.10_Linux_x86_64.tar.gz
Extracting /home/app/Downloads/k9s_v0.24.10_Linux_x86_64.tar.gz
Installing to /home/app/.local/opt/k9s-v0.24.10/bin/k9s
Installed 'k9s' v0.24.10 as /home/app/.local/bin/k9s
```

```bash
k9s version
```

```txt
 ____  __.________
|    |/ _/   __   \______
|      < \____    /  ___/
|    |  \   /    /\___ \
|____|__ \ /____//____  >
        \/            \/

Version:    v0.24.10
Commit:     6426ea112f0736d9b81da6dad5b6fa2cfe9b7fed
Date:       2021-05-20T05:55:21Z
```

**Comment by coolaj86** [comment]
Perhaps you used some other install method previously and have a custom `PATH` configuration such that the prior version of `k9s` is what takes priority?

```bash
command -v k9s
```

```txt
/home/me/.local/bin/k9s
```

**Comment by coolaj86** [comment]
Closing because I believe this is a system-specific error, but feel free to re-open if closer examination reveals that to not be the case.

**Comment by mpouleijn** [comment]
I have a similar issue I'm on ubuntu 20.04 any idea?

➜  michelp webi k9s

Thanks for using webi to install 'k9s' on 'linux/amd64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

switched to 'k9s' v0.24.14 at /home/michelp/.local/opt/k9s-v0.24.14/bin/k9s
➜  michelp k9s version
```
 ____  __.________
|    |/ _/   __   \______
|      < \____    /  ___/
|    |  \   /    /\___ \
|____|__ \ /____//____  >
        \/            \/

Version:    v0.24.11
Commit:     9b498196f908ef2ceb4b02b065818485e8efe19f
Date:       2021-06-28T05:23:25Z
```

➜  michelp /home/michelp/.local/opt/k9s-v0.24.14/bin/k9s version
```
 ____  __.________
|    |/ _/   __   \______
|      < \____    /  ___/
|    |  \   /    /\___ \
|____|__ \ /____//____  >
        \/            \/

Version:    v0.24.11
Commit:     9b498196f908ef2ceb4b02b065818485e8efe19f
Date:       2021-06-28T05:23:25Z
```
