### ISSUE TITLE
Complementary files (man, bash_completion, etc) installation

### ISSUE THREAD

**Issue by iamc** [webinstall/webi-installers#245]
I see that most, if not all, the installers do not install neither man pages, nor bash, zsh etc. completion files when available. Would PRs covering this be accepted?

**Comment by coolaj86** [comment]
Hi @aimc,

I thought I had responded to this... a year ago.

Yes, that would be acceptable. I believe the appropriate locations would be `~/.local/opt/MY_PACKAGE/share/man/` (which seems to be a pattern picked up by `manpath` automatically) and `~/.local/share/man/`.

**Comment by coolaj86** [comment]
Here's the instructions:
https://github.com/webinstall/webi-installers/issues/338

PRs welcome.

I'll close out this issue though.
