### ISSUE TITLE
[Bug] get an error when starting win.terminal, can´t find font

### ISSUE THREAD

**Issue by Christian-Rau** [webinstall/webi-installers#246]
## What were you trying to install (or what else went wrong)?
Followed the "tutorial"
___
Install Nerd Font
Paste this into a Command or cmd.exe prompt.

___

## What exactly did you do?

Pasted this into PS prompt.

`curl.exe -A "MS" https://webinstall.dev/nerdfont | powershell`

## What went wrong?

It broke my font settings, so that the **droidsansmono NF** didn't load and get an error when starting win.terminal

It couldn't find it

## Which OS did you try on?

- [ ] Mac
- [x] Windows
- [ ] Linux

21H1 build 19043.985

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
It should have opened the font book, prompting you to click the "Install" button in the GUI to finish the installation. Did that happen?

What do you mean it "broke" your font settings?

**Comment by coolaj86** [comment]
I think this was fixed a few days ago by a PR. The issue appeared to be some bad whitespace that (surprise) I didn't see.
