### ISSUE TITLE
[Bug] Website: Firefox 89 "copy to clipboard" button under command doesn't work

### ISSUE THREAD

**Issue by creedasaurus** [webinstall/webi-installers#263]
## What were you trying to install (or what else went wrong)?
Anything. Although this is really simple and I dont often use the button. I just noticed it didn't work on Firefox, so it may confuse some people.

## What exactly did you do?
Clicked the "Copy" button on https://webinstall.dev/jq/

## What went wrong?
No page indication of anything, other than when you go to paste, it is just the previous item on your clipboard.

Browser console output:

```
Uncaught (in promise) TypeError: 'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    copy https://webinstall.dev/dist/app.js:2
    setTimeout handler*copy https://webinstall.dev/dist/app.js:2
    click https://webinstall.dev/dist/app.js line 2 > Function:3
    Be https://webinstall.dev/dist/app.js:2
    n https://webinstall.dev/dist/app.js:2
    _wrapper https://webinstall.dev/dist/app.js:2
    Kr https://webinstall.dev/dist/app.js:2
    it https://webinstall.dev/dist/app.js:2
    Jr https://webinstall.dev/dist/app.js:2
    y https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    h https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    h https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    h https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    h https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    Ii https://webinstall.dev/dist/app.js:2
    _update https://webinstall.dev/dist/app.js:2
    r https://webinstall.dev/dist/app.js:2
    get https://webinstall.dev/dist/app.js:2
    ln https://webinstall.dev/dist/app.js:2
    mount https://webinstall.dev/dist/app.js:2
    $mount https://webinstall.dev/dist/app.js:2
    $mount https://webinstall.dev/dist/app.js:2
    init https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    h https://webinstall.dev/dist/app.js:2
    f https://webinstall.dev/dist/app.js:2
    Ii https://webinstall.dev/dist/app.js:2
    _update https://webinstall.dev/dist/app.js:2
    r https://webinstall.dev/dist/app.js:2
    get https://webinstall.dev/dist/app.js:2
    ln https://webinstall.dev/dist/app.js:2
    mount https://webinstall.dev/dist/app.js:2
    $mount https://webinstall.dev/dist/app.js:2
    $mount https://webinstall.dev/dist/app.js:2
    <anonymous> https://webinstall.dev/dist/app.js:2
    <anonymous> https://webinstall.dev/dist/app.js:2
    <anonymous> https://webinstall.dev/dist/app.js:2
app.js:2:94249
```

## Which OS did you try on?

- [x] Mac
- [ ] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by ryanburnette** [comment]
I'm on it.

**Comment by creedasaurus** [comment]
Oh, not sure if it's also a bug, or expected, but on Safari, the button doesn't even show. I guess it's better that it not show if it can't work, but if it's not a hard fix, could be useful, haha!

**Comment by ryanburnette** [comment]
It's been on my to-do list to improve the copy to clipboard feature anyway. I need to update it and do some more testing. Thanks for opening the issue.

**Comment by zvakanaka** [comment]
Same problem:

Firefox version: 98.0b7
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
OS: macOS Big Sur (version 11.6.4)

**Comment by starvader13** [comment]
Is this fixed or still open @creedasaurus ? I would love to have a look at this issue...

**Comment by coolaj86** [comment]
@starvader13 Please take a look and let me know what you see.

**Comment by coolaj86** [comment]
> Thank heavens as of June 2024, the ability to "Copy" in a browser has finally landed as "Baseline" support for Evergreen browsers: <https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write>
> 
> Who could have imagined that we'd ever see the day!?
> 
> Anyway, I updated the site and tested in Chrome, Firefox, and Safari. I can't believe it, but it works!

Copied from #818.
