### ISSUE TITLE
[Installer] setcap convenience util

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#271]
A setcap convenience util would be nice that runs setcap for 80,443 services as non-root. Would also be nice if it resolves the file through symlinks for the setcap command.

```bash
sudo setcap 'cap_net_bind_service=+ep' $(readlink -f $(which caddy))
```

**Comment by ryanburnette** [comment]
@coolaj86 Feedback?

**Comment by coolaj86** [comment]
I actually almost did this way back when.

In fact, I _did_ write this! https://github.com/webinstall/webi-installers/tree/main/vps-utils

But my hangup is this: How to make a name for the utility that is easy to remember and type?

- `netcap`?
- `netbind`?

The problem with `setcap` is only that it does _lots_ of different things, but people like you and I only ever use it for this _one_ thing.

Also, this is already built into `serviceman`, so you don't need to deal with setcap directly unless you're not using `serviceman`.

**Comment by coolaj86** [comment]
We should call it `setcap-netbind`. Solved. Done.

**Comment by coolaj86** [comment]
@ryanburnette Want to make a PR to change the one in vps-utils over to `setcap-netbind`?

**Comment by ryanburnette** [comment]
Sure.

**Comment by ryanburnette** [comment]
See #273
