### ISSUE TITLE
[Bug] webi should install to /usr/local/bin on macOS

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#275]
On macOS, `~/.local/bin` is not included in `$PATH` by default. We should put executables in `/usr/local/bin` instead (does not require `sudo`).

**Comment by coolaj86** [comment]
Writing to `/usr/local` does require `sudo`.

`webi` uses `pathman` to update `$PATH`. You should see the message printed out that you need to `export PATH="$HOME/.local/bin:$PATH", or open and close your terminal on the _first run_ only.

**Comment by ajeetdsouza** [comment]
Homebrew stores binaries in `/usr/local/bin` without `sudo`. I suppose it wouldn't work in multi-user setups unless you were added to the correct group, so perhaps `~/.local/bin` is the best way.

**Comment by coolaj86** [comment]
> Homebrew stores binaries in `/usr/local/bin` without `sudo`. 

Actually homebrew requires `sudo` to install itself, and changes `/opt/Brew` and `/usr/local`.

**Comment by ajeetdsouza** [comment]
I have a new macOS system with Homebrew, but my `/opt` directory is empty, even though I have several casks and command-line tools installed. The binaries are stored in `/usr/local/Cellar/`, and symlinks to those binaries are placed in `/usr/local/bin/`, so that they work with `$PATH`. Perhaps they changed the location recently?

I was confused because I tried `touch /usr/local/bin/foo` and it worked without `sudo`, but that's probably because my system is set up with a single user and I'm the owner of `/usr/local/bin`. It probably works differently with a multi-user setup.

**Comment by coolaj86** [comment]
Oh, I think I got mixed up about `/opt/Brew` and

```txt
/usr/local/Caskroom
/usr/local/Cellar
/usr/local/opt/* => /usr/local/Cellar/*
/usr/local/Homebrew
```

In any case, I firmly believe that on Mac, Linux, and Windows, the home directory is the right place to put local installs are guaranteed to be conflict-free for any system-level tools.

I know I've had permission problems with `/usr/local` on OS X (between node, go, and brew fighting over each other), but I don't know if I've tested since the switch `macOS`.
