### ISSUE TITLE
[Bug] webinstall.dev/zoxide appears to be broken

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#279]
From: https://github.com/ajeetdsouza/zoxide/issues/245

> It seems the URL to install zoxide is broken.
> 
> ```
> curl -sS https://webinstall.dev/zoxide | bash
> ```
> 
> The URL gives:
> 
> ```
> Cannot GET /zoxide
> ```
> 
> Run the command shows:
> 
> ```
> "zoxide" Not found.
>  
> See https://webinstall.dev/ for featured installers
> or https://webinstall.dev/sitemap.xml for a list of all installers
>  
> Think "zoxide" is something we should have? Let us know:
>  
>   https://github.com/webinstall/webi-installers/issues/new?title=Add%20zoxide
> ```

CC @coolaj86

**Comment by coolaj86** [comment]
Sorry about that.

I'm not exactly sure what happened, but prod had deployed `hotfix`, which is lagging behind `main`. Prod is back on `main` again and `hotfix` is now up-to-date.
