### ISSUE TITLE
`gh` Needs a Cheat Sheet

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#281]
The installer has been done (#230, #237) and can be previewed at <https://beta.webinstall.dev/gh>

Now we just need someone to fill out the **Cheat Sheet**:

Just edit this README, and add the goodies that are the most useful for you (and that you think will be the most useful to others): https://github.com/webinstall/webi-installers/blob/add-gh/gh/README.md

A TL;DR sort of thing would be great. :)

P.S. Here's are what good cheat sheets look like:

- https://webinstall.dev/node/
- https://webinstall.dev/rg/

**Comment by khairnarsaurabh23** [comment]
@coolaj86 can i work on this issue?

**Comment by coolaj86** [comment]
Please do!

**Comment by coolaj86** [comment]
Closed via https://github.com/webinstall/webi-installers/pull/302
