### ISSUE TITLE
Fedora: hangs at "Downloading serviceman from ..."

### ISSUE THREAD

**Issue by nyjel** [webinstall/webi-installers#291]
Hi.  I have Fedora 33 running on an AMD Ryzen 5 desktop, and I was hoping to use webi to install serviceman.

I installed webi via:  

```
curl -sS https://webinstall.dev/webi | bash
```

No issues.

I then tried installing serviceman:

```
 webi serviceman

Thanks for using webi to install 'serviceman' on 'linux/amd64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Downloading serviceman from
https://github.com/therootcompany/serviceman/releases/download/v0.8.0/serviceman_0.8.0_linux_x86_64.tar.gz
```

It hangs on this line for a long time.  I see that the Download ( .part) is hung at size 0.

I have no problem downloading this file via curl...

```
curl -O https://github.com/therootcompany/serviceman/releases/download/v0.8.0/serviceman_0.8.0_linux_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   644  100   644    0     0   3023      0 --:--:-- --:--:-- --:--:--  3023
```

Any idea what might be causing the dowload to hang ?  I really like the idea of webi, as a developer, and would like to get it working on my system.

Thanks -- Nigel

**Comment by coolaj86** [comment]
I'm assuming you tried more than once and it hung every time?

Check to see if you have `wget` installed:

```bash
command -v wget
```

If you don't, try installing it, and then run the webi command again:

```bash
sudo dnf install wget

webi serviceman
```

I'll also spin up fedora on Digital Ocean and see what I see. I pretty much exclusively use Ubuntu.

**Comment by coolaj86** [comment]
Also, could you try installing something else, such as `rg`?

```bash
webi rg
```

**Comment by coolaj86** [comment]
Since I never got feedback on this, I'm closing it out.

Please reopen if it's still an issue.
