### ISSUE TITLE
Windows webi install - pathman-setup.ps1 is not recognized

### ISSUE THREAD

**Issue by rsrini7** [webinstall/webi-installers#293]
## What were you trying to install (or what else went wrong)?

Install in windows

## What exactly did you do?

curl.exe -A "MS" https://webinstall.dev/webi | powershell

## What went wrong?

▶ & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" "webi"
.\.local\tmp\pathman-setup.ps1 : The term '.\.local\tmp\pathman-setup.ps1' is not recognized as the name of a cmdlet
![2021-08-24 07_35_30](https://user-images.githubusercontent.com/5178105/130544458-304c5308-b68d-48f4-94cc-7a6cb43cfb48.png)

## Which OS did you try on?

- [ ] Mac
- [X] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Closing in favor of #300. Seems to be the same issue. Needs investigation.

**Comment by coolaj86** [comment]
@rsrini7 I think I've solved the issue. Did you happen to be using PowerShell as admin?

If so, can you confirm that running as a normal user fixes the problem?

See <https://github.com/webinstall/webi-installers/issues/300#issuecomment-976332468>.
