### ISSUE TITLE
How to download Hugo with SASS support?

### ISSUE THREAD

**Issue by goldcoders** [webinstall/webi-installers#297]
is it possible to download extended version?

**Comment by coolaj86** [comment]
Is there an API for versions with extensions?

I just use the stock version for myself, and I'm not into the Hugo community. Tell me more.

It may be possible to use semver build tags for this, such as:

```
webi hugo@v0.62+abc+xyz
```

However, it would require understanding how to fetch those versions from whatever build server is out there for this purpose.

**Comment by goldcoders** [comment]
the only difference is the naming,
if it is extended version it uses
hugo_exteded
if normal hugo
hugo

so it will be 

hugo_extended@v0.87 for extended

and hugo@v0.87

**Comment by coolaj86** [comment]
Closing in favor of https://github.com/webinstall/webi-installers/issues/324
