### ISSUE TITLE
[Bug] webi doesn't upgrade a package if it's already downloaded before

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#303]
## What were you trying to install (or what else went wrong)?

zoxide

## What exactly did you do?

I had installed zoxide v0.7.2 earlier via webi. Now I ran the same command, hoping that webi would upgrade zoxide to v0.7.6:

```sh
curl https://webinstall.dev/zoxide | bash
```

## What went wrong?

zoxide's tarballs from GitHub do not include the version number -- they're all named `zoxide-x86_64-unknown-linux-musl.tar.gz`.
- The first time I downloaded zoxide via webi, it created the file `~/Downloads/zoxide-x86_64-unknown-linux-musl.tar.gz`. This was version v0.7.2.
- The next time I downloaded zoxide, it did not actually download anything because `~/Downloads/zoxide-x86_64-unknown-linux-musl.tar.gz` already existed. Then it extracted the same tarball out to `~/.local/opt/zoxide-v0.7.6/bin/zoxide`.

As a result:

```sh
$ /home/ajeet/.local/opt/zoxide-v0.7.6/bin/zoxide --version
zoxide v0.7.2
```

webi should overwrite the previous file if it already exists.

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by ajeetdsouza** [comment]
I've already updated zoxide to include version numbers in its release tarballs.

However, I'm proposing that we _overwrite_ old downloads rather than assume that they can be re-used:
- The user may be re-running the command because the previous download was a corrupted file.
- Some software like `tokei`, `zoxide`, `rust-analyzer` do not include the version number in their tarballs, causing this bug to occur.

---

On a related note, I still feel we should download to `/tmp` rather than `~/Downloads`. We anyway have each version of the downloaded packages backed up under `~/.local/opt`. Keeping a copy in `~/Downloads` means we end up storing _yet_ another copy of the same package, and we also end up cluttering up the user's `Downloads` folder.

**Comment by coolaj86** [comment]
@ajeetdsouza The upgrade bug should be fixed by the combination of these two updates: 
- https://github.com/webinstall/webi-installers/pull/326
- https://github.com/webinstall/webi-installers/pull/284

Please double check on your end and let me know.
