### ISSUE TITLE
[Bug] zoxide installation is broken

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#310]
## What were you trying to install (or what else went wrong)?

zoxide

## What exactly did you do?

`curl https://webinstall.dev/zoxide | bash`

## What went wrong?

```
$ curl -sS https://webinstall.dev/zoxide | bash


Thanks for using webi to install 'zoxide@stable' on 'Linux/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Found /home/scottjl/Downloads/zoxide-v0.7.9-x86_64-unknown-linux-musl.tar.gz
Extracting /home/scottjl/Downloads/zoxide-v0.7.9-x86_64-unknown-linux-musl.tar.gz
Installing to /home/scottjl/.local/opt/zoxide-v0.7.9/bin/zoxide
mv: cannot stat './zoxide-*/zoxide': No such file or directory
```

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

Original issue: https://github.com/ajeetdsouza/zoxide/issues/296

**Comment by Steph0** [comment]
+1
