### ISSUE TITLE
[Suggestion] Use CODEOWNERS to allow project maintainers to update their own installers

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#315]
We can use a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file to allow people to push changes to specific installers, without giving them access to the rest of them. Of course, allowing someone to edit an installer comes with obvious security issues, which is why I'm proposing we only allow maintainers of a project to edit the installers of their own project.

This would ease the maintenance burden for the owners of webi and allow faster updates for broken installers. Note that this is only useful if we have some kind of CI/CD to actually deploy the new installers on the site. I'd once again recommend GitHub Actions here if something like this isn't already set up.

**Comment by coolaj86** [comment]
This is an excellent idea!

I had no idea this existed.

Would you create a PR adding yourself to zoxide?

**Comment by ajeetdsouza** [comment]
I just read up a bit more about this. Apparently I misunderstood some things, so I'm clarifying:

- CODEOWNERS do not automatically get write access -- in fact, they must be _given_ write access to the entire repo. This can be made secure by making `main` a "protected branch", so that no one other than @coolaj86 can push to it. Other maintainers can push to other branches, but that would not pose a security problem.
- CODEOWNERS automatically get notified if there is a PR to any of their "owned" code. One can setup the repository such that PRs cannot be merged without a review from the CODEOWNER. This is apparently the only real advantage of CODEOWNERS.

With this in mind, I don't see a significant reason to add this anymore, so I'll close this issue. However, this would definitely be handy once the repository grows in size, so it's something to keep in mind for later. For example, [here](https://github.com/NixOS/nixpkgs/blob/master/.github/CODEOWNERS) is the CODEOWNERS file of nixpkgs.
