### ISSUE TITLE
[RPi] Needs fallback for various arm builds (aarch64, armv7, armv6, armv5)

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#318]
## What were you trying to install (or what else went wrong)?

zoxide

## What exactly did you do?

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

## What went wrong?

```
Thanks for using webi to install 'zoxide@stable' on 'Linux/armv7l'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/packages/issues

Error: no 'zoxide' release for 'linux' on 'armv7l' as one of 'tar,exe,zip,xz,git,dmg' by the tag ''
       'zoxide' is available for 'macos,windows,linux' on 'arm64,amd64' as one of 'tar,zip,exe'
       (check that the package name and version are correct)

       Double check at https://webinstall.dev/api/releases/zoxide@.tab
```

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ ] Laptop or Desktop (amd64 / x86-64)
- [x] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

Original issue: https://github.com/ajeetdsouza/zoxide/issues/298

**Comment by coolaj86** [comment]
Did you have tar and/or zip installed?

(otherwise it can’t find a matching unarchive tool)

Does the reported architecture match an available architecture?

(raspbian reports armv5 - same as Pi Zero - which isn’t actually supported as well as arm64 and, in general, cannot be assumed to run arm64 binaries - such as on Pi Zero)

**Comment by ajeetdsouza** [comment]
@coolaj86 the Rust installer finds target triples very well. I'd suggest taking a look at the `get_architecture()` function in https://sh.rustup.rs.

**Comment by ajeetdsouza** [comment]
CC @piersolenski

**Comment by piersolenski** [comment]
> Did you have tar and/or zip installed?

Both are installed 👍

**Comment by ajeetdsouza** [comment]
@coolaj86 I think the problem here is that our matching logic for ARM targets needs to be more robust. We should try to find the binary with the exact ARM version (v6, v7, v8) and variant (`-l`, `-h`, etc) as the processor, but we should also fallback correctly if the exact version is unavailable.

For example, ARM v6 binaries work on ARM v7 processors. If armv7 has no match, we should look for armv6 instead.

**Comment by coolaj86** [comment]
@ajeetdsouza @piersolenski Will you test and see if `zoxide` (and whatever else you're interested in) now installs for you on raspberry pi?

For right now I'm using the same hacky-doo that I do for the M1 - try the binary that matches what `arch` reports and, if that can't be found, fallback to the other (either `aarch64` or `armv7l`).

I won't close this quite yet, because I don't think the fallback matching is complete (I don't handle armv6 or armv5).

**Comment by coolaj86** [comment]
I added the fallback for armv6. I'll wait to address armv5 until we see there's real interest for that.

Closing, but please test and verify. Thanks.

**Comment by ajeetdsouza** [comment]
I don't have an RPi myself. @piersolenski could you try this?

**Comment by piersolenski** [comment]
The installation works now, however I'm getting `/home/pi/.zshrc:87: exec format error: zoxide` (the line being `eval "$(zoxide init zsh)"`).

**Comment by coolaj86** [comment]
@piersolenski
1. What's the _actual_ CPU type of your RPi? (3+ is arm64, 2- is armv7-)
2. What's the OS you're using?
3. What's the output of `arch`?
4. What's the output of `uname -a`?
5. Do you have bionic enabled?

I'm using the 64-bit version of Ubuntu on my RPi an it works.

If you're running the 32-bit Raspbian I'm not sure what's supposed to happen - if the advice should be "enable bionic" or if we need a "try again" type of thing.

**Comment by piersolenski** [comment]
1. 
```
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03112
Serial          : 100000008852f600
Model           : Raspberry Pi 4 Model B Rev 1.2
```

2.

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

3. `armv7l`

4. `Linux bb 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`

**Comment by coolaj86** [comment]
Hey @ajeetdsouza What does `arm-unknown-linux-musleabihf` mean? Is that armv5? or arm64 hf?

Why do you put the `hf` after `musl` rather than like `armv7hf`?

```txt
https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.9/zoxide-v0.7.9-aarch64-unknown-linux-musl.tar.gz	
https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.9/zoxide-v0.7.9-x86_64-unknown-linux-musl.tar.gz	
https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.9/zoxide-v0.7.9-arm-unknown-linux-musleabihf.tar.gz	
https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.9/zoxide-v0.7.9-armv7-unknown-linux-musleabihf.tar.gz
```

**Comment by ajeetdsouza** [comment]
> Why do you put the `hf` after `musl` rather than like `armv7hf`?

It's a standard Rust target triple, all Rust projects have them. Here's a mapping of Rust target triples and their meanings: https://doc.rust-lang.org/nightly/rustc/platform-support.html

> What does `arm-unknown-linux-musleabihf` mean?

According to the page, `arm-unknown-linux-musleabihf` is ARMv6 with hardfloat.

**Comment by coolaj86** [comment]
@ajeetdsouza Thanks.

I wish everyone could just agree and use the same naming conventions... but alas... 

![](https://imgs.xkcd.com/comics/standards_2x.png)

**Comment by coolaj86** [comment]
Closing again because I think I've really fixed this time. Please check and confirm @piersolenski.

**Comment by coolaj86** [comment]
P.S. Why are all linuxes "unknown"? Are there any "known" linuxes?

**Comment by ajeetdsouza** [comment]
@coolaj86 that's the vendor name.

This isn't something Rust-specific -- the Rust compiler (like most compiled languages) uses a backend called LLVM for generating assembly. Rust essentially inherits target triples from LLVM itself: https://clang.llvm.org/docs/CrossCompilation.html#target-triple

**Comment by piersolenski** [comment]
@coolaj86 it's working! woop woop! thanks dude!
