### ISSUE TITLE
[Internal] Cleanup & Style

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#325]
These are tasks that anyone could help with.

- [x] #393
- [x] #394
- [x] `shfmt` all files
   ```bash
   fd -e sh -0 | xargs -0 shfmt -w -i 4 -sr -ci -s
   ```
- [x] Lint all *.sh files (with shellcheck & shfmt). Most install.sh files should disable unexported var warnings
   ```bash
   # shellcheck disable=SC2034
   #  "'pkg_cmd_name' appears unused. Verify it or export it."
   ```
- [x] All bash scripts should begin with `#!/bin/bash`
- [x] All functions in the `*/*.sh` files should be explicitly declared as functions
   ```bash
   # ✅ correct
   function pkg_install() {
       # ...
   }
   ```
   ```bash
   # ❌ incorrect
   pkg_install() {
       # ...
   }
   ```
- [x] All installers should have a wrapper function
   ```bash
   # ✅ correct
   #!/bin/bash
   set -e
   set -u
   
   function __install_foobar() {
       # ...
   }
   __install_foobar
   ```
   ```bash
   # ❌ incorrect
   #!/bin/bash
   set -e
   set -u
   {
       # ...
   }
   ```
- [x] ~~All conditionals should be in the format `if [[ expr ]]; then`, not `if [ expr ]; then`~~ (reverse that, we are POSIX!)
- [x] #395
- [ ] #660
   ```txt
   ~/.bashrc
   ~/.config/envman/PATH.env
   ~/.local/bin/rg
   ~/.local/opt/rg/
   ~/.local/opt/rg-{version}/
   ```
- [ ] Move `pkg_get_current_version` command to cheat sheet

**Comment by y0rune** [comment]
Hi!
I created the https://github.com/webinstall/webi-installers/pull/330. Please check if my changes are correct. 
Thank you ;)
