### ISSUE TITLE
[windows] Should warn if run as Admin

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#350]
It's important that Webi NOT be run as Admin - otherwise the ENVs get messed up and it won't work. \
(it's really late, but that should be coherent enough for me to understand in the morning)

Re #300

**Comment by devPalacio** [comment]
something like this could go somewhere in the code...maybe after thanksgiving.

function Confirm-IsElevated
{
    $id = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $p = New-Object System.Security.Principal.WindowsPrincipal($id)
    if ($p.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator))
        { Write-Output $true }      
    else
        { Write-Output $false }   
}

if(Confirm-IsElevated)
    { throw "Please run script NOT as administrator" }
