### ISSUE TITLE
[Bug] installing k9s for windows fails

### ISSUE THREAD

**Issue by koddistortion** [webinstall/webi-installers#360]
## What were you trying to install (or what else went wrong)?

I was trying to install **k9s** for Windows (x64 Desktop device)

## What exactly did you do?

As stated in the instructions of the [README.md from k9s](https://github.com/derailed/k9s#installation), I ran `curl.exe -A MS https://webinstall.dev/k9s | powershell`

## What went wrong?

After installing the necessary tools, downloading of k9s release fails:
`curl: (6) Could not resolve host: Windows`

## Which OS did you try on?
- [ ] Mac
- [x] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?
- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by koddistortion** [comment]
I created a pull request, see https://github.com/webinstall/webi-installers/pull/361

**Comment by coolaj86** [comment]
Merged. Thank you @koddistortion!
