### ISSUE TITLE
[Bug] Didn't see version when I installed jq on ubuntu 

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#373]
## What were you trying to install (or what else went wrong)?

jq

## What exactly did you do?

webi jq

## What went wrong?

Version number is missing from line 3, but I can see it below.

<img width="663" alt="Screen Shot 2021-12-09 at 12 25 17" src="https://user-images.githubusercontent.com/2252601/145447930-3d7cc3cc-896e-444a-9f25-736a91b686e4.png">

## Which OS did you try on?

ubuntu

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

## Linked Issue

- [ ] #396

**Comment by coolaj86** [comment]
It's there. Look at the last line.

You didn't specify a tag, so the tag is empty. Perhaps we should put `foo@(any)` or just `foo` when a tag isn't specified.

**Comment by ryanburnette** [comment]
This is the intended behavior? Well, it makes no sense. I suggest etiher:

- remove the `@` if there's nothing after it because it looks like an error
- show the version after the `@`

**Comment by coolaj86** [comment]
closed in favor of #396
