### ISSUE TITLE
[Bug] Installer not exiting early on error

### ISSUE THREAD

**Issue by ajeetdsouza** [webinstall/webi-installers#375]
## What were you trying to install (or what else went wrong)?

zoxide

## What exactly did you do?

```sh
curl -sS https://webinstall.dev/zoxide | bash
```

## What went wrong?

Related issue: https://github.com/ajeetdsouza/zoxide/issues/310

`pathman` did not have an arm64 binary. The installer should have exited early upon error, but that didn't happen. It printed out the success message instead. I've created a separate issue to fix the root cause of the problem here: https://git.rootprojects.org/root/pathman/issues/5.

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ ] Laptop or Desktop (amd64 / x86-64)
- [x] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
`pathman` is removed when #505 lands in production (should be within 72 hours)
