### ISSUE TITLE
[Bug] Typo in jshint docs

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#376]
Both in https://github.com/webinstall/webi-installers/tree/main/jshint#how-to-set-jshints-defaults and in https://github.com/webinstall/webi-installers/blob/main/jshint/jshintrc.webi.json5

```bash
sed -e ~/.jshintrc.webi.json5 's://.*::g' > .jshintrc
```

should be

```bash
sed -e 's://.*::g' ~/.jshintrc.webi.json5 > .jshintrc
```

**Comment by masterYA** [comment]
@coolaj86 can I take this up?

**Comment by martroxxx** [comment]
can I be assigned, please?

**Comment by coolaj86** [comment]
Closed thanks to @SilverPoision and @builtbydans

**Comment by coolaj86** [comment]
@masterYA @martroxxx: There are a few other fairly easy issues in this repo. Check out: https://github.com/webinstall/webi-installers/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only

**Comment by coolaj86** [comment]
In particular, these are very, very easy: https://github.com/webinstall/webi-installers/issues/325

**Comment by SilverPoision** [comment]
> Closed thanks to @SilverPoision and @builtbydans

My pleasure!!

**Comment by SilverPoision** [comment]
> @masterYA @martroxxx: There are a few other fairly easy issues in this repo. Check out: https://github.com/webinstall/webi-installers/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only

I will surely have look.
