### ISSUE TITLE
[Bug] lsd - installer uses the gnu version where the musl version would be needed

### ISSUE THREAD

**Issue by Ognian** [webinstall/webi-installers#381]
## What were you trying to install (or what else went wrong)?

Installed lsd
But it installed the gnu version instead of the musl version.
(musl version works if installed manually)
OS is alpine based Linux (k3os)
Is there a way to manually override wich version should be installed?

## What exactly did you do?

curl -sS https://webinstall.dev/lsd | bash

## What went wrong?

```
Found /home/rancher/Downloads/webi/lsd/0.20.1/lsd-0.20.1-x86_64-unknown-linux-gnu.tar.gz
``` 
it installed the **gnu** version instead of the **musl** version (the musl version works when downloaded manually)

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [ x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [ ] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ x] Other (please specify, if you know) VM

**Comment by coolaj86** [comment]
Closing because we fixed this many moons ago.

I just tested on alpine to be double sure, and it is working now.

Thanks for the report @Ognian. Sorry we didn't tell you when we fixed it.

Re: #259 #485
