### ISSUE TITLE
Request for vim-commentary installer

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#386]
Formal request for [vim-commentary](https://github.com/tpope/vim-commentary) installer.

Should we put it in vim-essentials?

**Comment by khairnarsaurabh23** [comment]
Can you please explain in which directory the changes expected?

**Comment by ryanburnette** [comment]
This is a note to self. I'll take care of it.

**Comment by ryanburnette** [comment]
#389
