### ISSUE TITLE
[Bug] curl: (23) Failure writing output to destination

### ISSUE THREAD

**Issue by cawoodm** [webinstall/webi-installers#387]
## What exactly did you do?

```
curl https://webinstall.dev/webi | bash
```

## What went wrong?

```
curl: (23) Failure writing output to destination
error fetching 'https://webinstall.dev/api/installers/webi@stable.sh?formats=tar,exe,zip,xz,git,dmg'
```
As root, sudo, whatever makes no difference.

## Which OS did you try on?

Ubuntu 21.10 (minimal)

- [ ] Mac
- [ ] Windows
- [X] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by devPalacio** [comment]
webi is not meant to be installed as an elevated user. have you tried installing it without root or sudo?

**Comment by coolaj86** [comment]
What's the Linux distro? Is normal `bash` available?

Could you try installing `wget` and see if it works after that? (the script will auto-detect `wget` and prefer to use it when available).

If `wget` fails, then perhaps we'll at least get a better error message.

> curl: (23) Failure writing output to destination

It's hard to tell with so little information, but I wonder if perhaps `/tmp` is out of space or `~/.local` doesn't have write permissions.

**Comment by cawoodm** [comment]
I ran the command again and it worked now. I seem to remember we did have a machine which ran out of disk space. This could be the reason!
