### ISSUE TITLE
Move all "shmatter" (bash-frontmatter) to README.md frontmatter

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#393]
1. [ ] Identify each file that has "shmatter" in the `install.sh` and move it to YAML in `README.md`
   `install.sh`:
   ```bash
   # ❌ incorrect
   #!/bin/bash
   # title: My Title
   # description: A nice description...
   ```
   `README.md`:
   ```mkdn
   ---
   correct: ✅
   title: My Title
   description: A nice description...
   ---
   ```

**Comment by martijnhabers** [comment]
Hey @coolaj86 , first timer in contributing to open source here! Can I please get this assigned?

**Comment by y0rune** [comment]
Hello!
I tried to solve that issue with 
```bash
for i in $(grep -ir --color=no '# title' | cut -d ':' -f1); do (echo '---'; grep --color=no -iE '\#' $i | sed '/bin\/bash/d' | sed 's/# //g'; echo '---') > $(dirname $i)/README.md; sed -i '' '/title: /d;/description: /d;/homepage: /d;/tagline: /d; /alias: /d; /See /d' $i ; done
```
The PR: https://github.com/webinstall/webi-installers/pull/406

If someone has a better solution please share ;) 

Thank you ;)
