### ISSUE TITLE
Update all scripts to use `set -e; set -u` (except where noted otherwise)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#394]
All .sh files should start with the "strict bash" settings:

```bash
#!/bin/bash
set -e
set -u

# ...
```

1. Get a list of all `.sh` files:
   ```bash
   find . | grep '\.sh$' | sort -u > all-sh-files.txt
   ```
2. Get a list of `.sh` files that already have `set -e`:
   ```bash
   grep 'set -e' -r | cut -d ':' -f1 | sort -u > set-e-sh-files.txt
   ```
3. Update the files that are missing `set -e`:
   ```bash
   diff -y --suppress-common-lines all-sh-files.txt set-e-sh-files.txt
   ```
4. Run the formatter: `npm run shfmt`

**Comment by RishiKumarRay** [comment]
I did as instructed but getting this error
![Uploading Screenshot from 2022-02-01 14-57-43.png…]()

**Comment by y0rune** [comment]
Hello!
I created the https://github.com/webinstall/webi-installers/pull/399. I used the one line script in the my Mac. When I tried to used sed as I know in the linux gnu it was a little bit change in the MacOS

```bash
yorune@MacBook ~/git/dev/webi-installers main $ find . | grep --color=no '\.sh$' | sort -u > all-sh-files.txt; grep 'set -e' --color=no -r | cut -d ':' -f1 | sort -u > set-e-sh-files.txt; for i in $(diff -y  --suppress-common-lines all-sh-files.txt set-e-sh-files.txt | awk '{print $1}' | sed '/example/d;/>/d'); do sed -i '' '/set \-e/d;/set \-u/d' $i; sed -i '' '1a\
set -e\
set -u\
' $i; done
```

If someone find the wrong logic in my idea let me know.

Thank you ;)
