### ISSUE TITLE
Don't show '@' version/tag suffix when the tag is empty

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#396]
If you specify a tag (such as a version) when installing, you'll see that tag in the output, like so:

```txt
webi rg@13

Thanks for using Webi to install 'rg@13'
...
```

However, there are a places in the bash scripts (and possibly in powershell too) where the `@` is output even when the tag is empty, like this:

```txt
webi rg

Thanks for using Webi to install 'rg@'
...
```

We could probably create a new variable - say WEBI_AT_TAG - which is an empty string if the tag is empty, or the version / tag with the `@` prefix otherwise.

See #373.

## Level of Experience to Solve

Anyone with basic bash knowledge (variables, strings, etc) can fix this.

**Comment by Zach-Clay** [comment]
Hi! I am working on an open source project for my software development methodologies class and I would like to be assigned to this issue! Since I am not very familiar with this projects codebase, what file/files should I take a look at to get started with this issue? Thank you for your time.

**Comment by coolaj86** [comment]
I think everything is under the `_webi` folder, probably the 'template' and 'bootstrap' files.

You do need to be familiar with bash to accomplish this.
(and it would be great if you can do the same for powershell)

**Comment by vxhl** [comment]
Hello! Since Zach removed his assignment from this issue could you please assign it to me?

**Comment by vxhl** [comment]
Hey @coolaj86. I've been exploring the code for some time now. I found the file with the problem which is `bootstrap.sh` but I can't seem to understand how to exactly implement the condition that you said? 

> We could probably create a new variable - say WEBI_AT_TAG - which is an empty string if the tag is empty, or the version / tag with the @ prefix otherwise.

Please help me understand what I am missing here. I tried to understand line 63 in `template.sh` which may be the key to fixing this but I'm not entirely sure. 

Also `releases.js` has the following line 189

` "WEBI_PKG='" + pkg + '@' + ver + "'"`

Of course, just removing the `@` here won't solve the issue. So please guide me on what I need to learn for fixing this.

**Comment by coolaj86** [comment]
@vxhl Sorry I wasn't able to provide guidance on this at the time.

Here's the solution I went with: 

- `pkg` should always be set
- if `ver` is set, add the `@`

https://github.com/webinstall/webi-installers/pull/458/files
