### ISSUE TITLE
[Bug] Pathman installation is broken

### ISSUE THREAD

**Issue by soyo42** [webinstall/webi-installers#402]
## What were you trying to install (or what else went wrong)?

pathman

## What exactly did you do?
```
curl -sS https://webinstall.dev/pathman | bash
```

## What went wrong?
```
Downloading pathman from
https://git.rootprojects.org/attachments/249152de-7cd1-4b82-8223-d21b05e35a42
ssl_client: git.rootprojects.org: ocsp verify failed: ocsp response not current
wget: error getting response: Connection reset by peer
failed to download from https://git.rootprojects.org/attachments/249152de-7cd1-4b82-8223-d21b05e35a42
```
wget --version :
- GNU Wget 1.21 built on linux-gnu.
- BusyBox v1.32.1 () multi-call binary.

After hacking wget away - curl did the job. 

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Thanks for the report.

This is now fixed.

There was a security issue with _Let's Encrypt_ this past week, resulting in millions of SSL certificates being revoked. The certificate for git.rootprojects.org wasn't automatically renewed:

> ssl_client: git.rootprojects.org: ocsp verify failed: ocsp response not current

I manually renewed it and I've created a To-do #403 for moving pathman to GitHub releases.

**Comment by soyo42** [comment]
Thank you very much.
