### ISSUE TITLE
incorrect verbiage in website FAQ

### ISSUE THREAD

**Issue by benatkin** [webinstall/webi-installers#435]
In the FAQ:

> - webi doesn’t modify your system settings
> - webi doesn’t need `root`, `sudo`, or Admin privileges
> - webi doesn’t need ruby/node/python/C# etc
> - webi doesn't require special shell functions to switch versions
> - webi create conflicts between installed versions (100% isolated, conflict-free)
> - webi doesn’t bulk update dependencies, or anything
> - webi doesn’t restrict the number of packages you can install simultaneously
> - webi doesn’t require documentation

It should say:

> - webi **doesn't** create conflicts between installed versions (100% isolated, conflict-free)

**Comment by coolaj86** [comment]
Indeed! I actually noticed that the other night. Thanks for the reminder!

...

Fixed!
