### ISSUE TITLE
Hugo install failed on Linux / Github Actions

### ISSUE THREAD

**Issue by DBBrowne** [webinstall/webi-installers#447]
## What were you trying to install (or what else went wrong)?

Hugo

I haven't tested this beyond re-running the task on GH-Actions:

Script:
https://github.com/DBBrowne/blog/blob/main/scripts/install-deps.sh

Failure:
https://github.com/DBBrowne/blog/runs/6609639460?check_suite_focus=true

## What exactly did you do?

Running install-deps.sh on Github Actions from the BeyondCode Bliss template.

## What went wrong?

Failed to install:
```
Error: no 'hugo' release for 'linux' on 'amd64' as one of 'tar,exe,zip,xz,git,dmg' by the tag ''
       'hugo' is available for 'freebsd,linux,macos,windows' on 'amd64,x86,arm64' as one of 'tar,zip'
       (check that the package name and version are correct)

       Double check at https://webinstall.dev/api/releases/hugo@.tab
```
## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux - Github Actions

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64) - Github Actions
- [ ] Raspberry Pi (ARM-64)
- [x] Other (please specify, if you know) - Github Actions

**Comment by coolaj86** [comment]
The error message _is_ wrong. There have been so many releases since Hugo v0.86 that it no longer shows up in the 1st page of paged output from GitHub Releases.

**Comment by coolaj86** [comment]
Semi-fixed via https://github.com/BeyondCodeBootcamp/bliss-template/commit/78f716c0ab0d4202eb89f615ecdd8846b281cf6a

Need to fix the error message to show the version rather than `''`.

**Comment by coolaj86** [comment]
I'm not sure which commit it landed in, but the error message was updated and now shows the correct tag:

```txt
Error: no 'hugo' release for 'linux' on 'amd64' as one of 'tar,exe,zip,xz,git,dmg' by the tag '0.86'
       'hugo' is available for 'freebsd,linux,macos,windows' on 'amd64,x86,arm64' as one of 'tar,zip'
       (check that the package name and version are correct)

       Double check at https://webinstall.dev/api/releases/hugo@0.86.tab
```
