### ISSUE TITLE
[Bug] k9s installer request hanging

### ISSUE THREAD

**Issue by StewartThomson** [webinstall/webi-installers#448]
## What were you trying to install (or what else went wrong)?

k9s

## What exactly did you do?

I ran `curl https://webinstall.dev/k9s | bash` to install k9s

## What went wrong?

Request to https://webinstall.dev/api/installers/k9s.sh?formats=tar,exe,zip,xz,git,dmg hangs indefinitely

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

Apologies if there is a better place I should have reported this

**Comment by 74Rog** [comment]
I've been having exactly the same issue since yesterday.

**Comment by tinhbuon1102** [comment]
Same here

**Comment by tereska** [comment]
same here

**Comment by coolaj86** [comment]
Looking into it...

**Comment by coolaj86** [comment]
Good news: A restart fixed it.

Bad news: A restart fixed it.

There's no special behavior for k9s as opposed to most of the other installers - which were still working - and I don't see anything immediately relevant in the error logs.

My best guess: unhandled network error resulted in async limbo.

I'll keep an eye out.

**Comment by dcrystalj** [comment]
I can confirm it started to work for me 🙄  
Bad news is that this might happen again without any particular useful message :(
