### ISSUE TITLE
Request for k9s

### ISSUE THREAD

**Issue by tinhbuon1102** [webinstall/webi-installers#449]
Hi today i try to install k9s via webi but not success. Seem you guy removed it ?

access : https://webinstall.dev/api/installers/k9s@stable.sh?formats=tar,exe,xz,git,dmg loading forever.

Pls add it to. Thank you

**Comment by coolaj86** [comment]
Good news: A restart fixed it.

Bad news: A restart fixed it.

There's no special behavior for k9s as opposed to most of the other installers - which were still working - and I don't see anything immediately relevant in the error logs.

My best guess: unhandled network error resulted in async limbo.

I'll keep an eye out.
