### ISSUE TITLE
Remove Bash-isms in favor of POSIX Shell

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#462]
This should be able to run on alpine in Docker and on all BSDs without issue.

All Bash-isms should be replaced with their POSIX Shell equivalents, including:

- [x] #463
- [x] #464
- [x] #465
- [x] #478
- [x] #479
- [x] #480
- [x] #481
- [x] #482
- [x] #494
- [x] #496 
   - update sub scripts and docs to use `sh`

```sh
fd -t f -e sh |
    xargs shellcheck -s sh -S warning -e SC2034 --
```

# Posix Resources

Posix Standard:
- Online: https://pubs.opengroup.org/onlinepubs/9699919799/
- HTML Download: https://pubs.opengroup.org/onlinepubs/9699919799/download/index.html ([.tar.gz](https://pubs.opengroup.org/onlinepubs/9699919799/download/susv4-2018.tgz))

Posix Shell ("Volume 3: Chapter 2: Shell Command Language"):
- https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html

Posix CoreUtils ("Volume 3: Chapter 4: Utilities")
- https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html

# Meta

`````mkdn
# What?

```diff
- old
+ new
```

# How

This could be done **by hand** or **by script**, and is probably as simple as installing [sd](https://webinstall.dev/sd) and committing the result of:

```sh
sd what ever
```

Some manual checks should be done as well - for which [rg](https://webinstall.dev/rg) can help.

```sh
rg thing
```

# Why?

As mentioned in #462, we want to move away from Bash-isms and towards plain POSIX-compliant shell usage.
`````

**Comment by y0rune** [comment]
Hello!
When I tried install the `webi` using a `curl https://webinstall.dev/webi | bash`. The system does not find a `bash` so I tried with `sh`.  The `webi` does not work. So I checked the shebangs and I found:
```
/ # cat /root/.local/bin/webi | head -n2
#!/bin/bash
``` 

So the questions:
- Do I have to install `bash` in the `Alpine` ?
- Do we have to change in the `webi` a shebangs from `/bin/bash` to `/bin/sh` ?

Thank you!

**Comment by coolaj86** [comment]
@y0rune In order to test properly the `#!/bin/bash` has to be changed to `#!/bin/sh` or `#!/usr/bin/env sh` in all of the files - but that can't be done until _all_ of the bashisms are removed.
