### ISSUE TITLE
[Doc] Change all code blocks from `bash` to `sh`

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#463]
# What?

Changing all of the READMEs and other `.md` (CommonMark / Markdown) files throughout the repo to use `` ```sh `` for shell code blocks:

`````diff
- ```bash
+ ```sh
`````

# How?

This could be done **by hand** or **by script**, and is probably as simple as installing [sd](https://webinstall.dev/sd) and committing the result of:

```sh
sd -s '```bash' '```sh' *.md */*.md */*.md
```

Some manual checks should be done as well - for which [rg](https://webinstall.dev/rg) can help.

```sh
rg '```bash'
rg '```sh'
```

# Why?

As mentioned in #462, we want to move away from Bash-isms and towards plain POSIX-compliant shell usage.

**Comment by MoNakouzi** [comment]
@coolaj86 I can work on this, please assign this to me.

**Comment by coolaj86** [comment]
@MoNakouzi Do it!

**Comment by MoNakouzi** [comment]
Completed and PR sent!
