### ISSUE TITLE
[Easy Refactor] Remove `function` prefix from all shell files (shellcheck SC2112)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#464]
# What?

The `function` prefix is optional for Bash functions, and should _not_ be used for Posix Shell functions. So we're making this change across the codebase:

```diff
- function do_something() {
+ do_something() {
```

# How?

This could be done **by hand**, or it could be done **by automation**, probably as simple as installing [sd](https://webinstall.dev/sd) and [fd](https://webinstall.dev/fd)  and committing the result of:

```sh
fd -t f -e sh | xargs sd 'function ([\w\-]+)\(' '$1(' --
```

Some manual checks should be done as well - for which [rg](https://webinstall.dev/rg) can help.

```sh
rg 'function'
```

# Why?

As mentioned in #462, we want to move away from Bash-isms and towards plain POSIX-compliant shell usage.

**Comment by brij-desaii** [comment]
Working on it

**Comment by MoNakouzi** [comment]
@coolaj86 Is this issue still unassigned? If so, please assign it to me

**Comment by coolaj86** [comment]
@MoNakouzi If you like you could fix https://github.com/webinstall/webi-installers/pulls.

I also added a bunch of others today:
https://github.com/webinstall/webi-installers/issues/462

**Comment by coolaj86** [comment]
@brij-desaii Thanks!

Drop your Đash Wallet address here (or DM me) and I'll send a tip / buy you lunch.

:)

**Comment by brij-desaii** [comment]
@coolaj86 Thanks for the offer but really I'm just happy to contribute :) This my first time contributing in the world of opensource and I learnt a lot!
