### ISSUE TITLE
Replace all `[[ ... ]]` conditions with `[ ... ]` conditions (`shellcheck` SC3010)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#465]
# What?

We need to switch out the bash-only `[[` in favor of `[` for compatibility with Alpine Docker and such. Basically something like this:

```diff
- [[ ! ... ]]
+ ! [ ... ]

- [[ ... || ... ]]
+ [ ... ] || [ ... ]

- [ ! ... ]
+ ! [ ... ] // or just `! ...` ? May need to be tested for correctness
```

It should be that only these files need updates:

```txt
_webi/bootstrap.sh
_webi/template.sh
brew/install.sh
git/install.sh
gpg-pubkey/gpg-pubkey.sh
gpg/install.sh
iterm2/install.sh
myip/myip.sh
python/install.sh
python2/install.sh
ssh-adduser/ssh-adduser.sh
test/install.sh
yq/install.sh
```

# How

This should probably be done by hand by checking each occurrence of the given warnings with [shellcheck](https://webinstall.dev/shellcheck):

```sh
# a specific file 
shellcheck -s sh -i SC3010 -- ./myip/myip.sh
```

```sh
# all files
shellcheck -s sh -i SC3010 -- *.sh */*.sh */*/*.sh
```

Each replacement should be checked against POSIX reference material, such as:
- http://mywiki.wooledge.org/BashFAQ/031
- http://mywiki.wooledge.org/BashPitfalls#A.5B.5B_.24foo_.3E_7_.5D.5D

# Why?

As mentioned in #462, we want to move away from Bash-isms and towards plain POSIX-compliant shell usage.

**Comment by MoNakouzi** [comment]
@coolaj86 If this is available, can I work on it?

**Comment by y0rune** [comment]
@MoNakouzi I am working on it here:https://github.com/webinstall/webi-installers/pull/468. The current status of it is blocked due to other issues. More info in the PR.

**Comment by coolaj86** [comment]
Finalized with #490 and #485.
