### ISSUE TITLE
refactor(posix): replace `==` bashism with posix `=` (`shellcheck` SC3014)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#478]
## Skills required

- command line
- shell scripting (i.e. bash, posix)
- git (obviously)

## What to do

1. Clone and enter the repo
   ```sh
   git clone https://github.com/webinstall/webi-installers.git ./webi-installers/
   cd ./webi-installers/
   ```
2. Install [`fd`](https://webinstall.dev/fd) and [`shellcheck`](https://webinstall.dev/shellcheck):
   ```sh
   curl -sS https://webinstall.dev/fd | bash
   curl -sS https://webinstall.dev/shellcheck | bash
   ```
3. Follow the on-screen instructions (or close and re-open the terminal)
   ```txt
   CLOSE AND RE-OPEN YOUR TERMINAL!
   ```
4. Find and fix the offending uses of `==`. \
    (you may find [`sd`](https://webinstall.dev/sd) useful to automate some of the find-and-replace work)
   ```sh
   fd -t f -e sh | \
       xargs shellcheck -s sh -S warning -i SC3014 --
   ```
   ```sh
   fd -t f -e sh -e md | xargs rg -- '=='
   ```

**Comment by MoNakouzi** [comment]
@coolaj86 please assign this to me!

**Comment by coolaj86** [comment]
@MoNakouzi It's yours!

**Comment by MoNakouzi** [comment]
@coolaj86 If I have a question about the task, should I post it here?

**Comment by coolaj86** [comment]
Yep.

**Comment by MoNakouzi** [comment]
Sounds good. So far, fd has been creating a binary file that is not executable (Exec format error) whenever I attempt to use it (including just 'fd'). I can't seem to figure out why this keeps happening. Do you have any ideas?

**Comment by coolaj86** [comment]
@MoNakouzi What environment are you on? Is there a download for it in <https://webinstall.dev/api/releases/fd.tab?pretty=true>?

You could use old-school `find`, you'd just need to lookup the equivalent options - I think it's `-type f -name='*.sh'`.

**Comment by MoNakouzi** [comment]
@coolaj86 Thank you, checking that the installation matches the OS made it work.

**Comment by MoNakouzi** [comment]
Completed and PR sent!

**Comment by coolaj86** [comment]
@MoNakouzi There seem to be two more instances:

```sh
rg '==' _webi/template.sh
```

```txt
184:            if [[ $- == *i* ]]; then
196:            if [[ $- == *i* ]]; then
```

As a follow-up those will need to be replaced with a `[` test, but I don't know how to do Posix substring matches and that can be saved for later.

**Comment by MoNakouzi** [comment]
@coolaj86 I'll fix those asap, thanks.

**Comment by MoNakouzi** [comment]
I added the correction to #488.
