### ISSUE TITLE
Style(sh): (easy) Remove wrapping around `if` blocks (shellcheck SC2143)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#500]
Re: #499 

1. Clone and enter the repo:
   ```sh
   git clone https://github.com/webinstall/webi-installers.git ./webi-installers/
   cd ./webi-installers/
   ```
2. Install [`shellcheck`](https://webinstall.dev/shellcheck) and [`shfmt`](https://webinstall.dev/shfmt):
   ```sh
   curl -sS https://webinstall.dev/shellcheck | sh
   curl -sS https://webinstall.dev/shfmt | sh
   ```
3. FOLLOW THE ON-SCREEN INSTRUCTIONS (from the installs)
4. Check all shell files for for redundant output checks
   ```sh
   shellcheck -s sh -iSC2143 *.sh */*.sh */*/*.sh
   ```
5. Update the `if` blocks according to the `schellcheck` suggestions. The necessary changes will be like this:
   ```diff
   - if [ -n "$(echo "$foo" | grep "bar")" ]; then
   + if echo "$foo" | grep -q "bar"; then
   ```
   - `grep` gets `-q`
   - `-n` will be removed
   - `-z` will be replaced with `!`
   - etc - see the instructions from `schellcheck`

**Comment by rishavnandi** [comment]
Hi, I want to pick this issue up..

**Comment by rishavnandi** [comment]
Hi, I want to take this issue up..
So as far as I understand I need to update the if blocks inside the shell files that are shown by the shellcheck command, right?

**Comment by coolaj86** [comment]
@rishavnandi This is being worked on in #501. You could collaborate on that, or you could do a similarly easy issue, like this one: https://github.com/webinstall/webi-installers/issues/503

**Comment by rishavnandi** [comment]
> @rishavnandi This is being worked on in #501. You could collaborate on that with @ShyamMahajan, or you could do a similarly easy issue, like this one: https://github.com/webinstall/webi-installers/issues/503

Thanks for the feedback I'll check it out!
