### ISSUE TITLE
lint(sh) (easy): Don't use variables in printf format strings (shellcheck SC2059)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#503]
Re: #499 

1. Clone and enter the repo:
   ```sh
   git clone https://github.com/webinstall/webi-installers.git ./webi-installers/
   cd ./webi-installers/
   ```
2. Install [`shellcheck`](https://webinstall.dev/shellcheck) and [`shfmt`](https://webinstall.dev/shfmt):
   ```sh
   curl -sS https://webinstall.dev/shellcheck | sh
   curl -sS https://webinstall.dev/shfmt | sh
   ```
3. FOLLOW THE ON-SCREEN INSTRUCTIONS (from the installs)
4. Check all shell files for for redundant output checks
   ```sh
   shellcheck -s sh -iSC2059 *.sh */*.sh */*/*.sh
   ```
5. Update printf strings from variable interpolation to variables substitution, according to the `schellcheck` suggestions. The necessary changes will look like this:
   ```diff
   - printf "Hello ${name}! Happy ${day}!"
   + printf "Hello %s! Happy %s" "${name}" "${day}"
   ```

**Comment by rishavnandi** [comment]
Hi, I have sent a PR kindly review it and lemme know if anything needs to be changed.
