### ISSUE TITLE
lint(sh): add comments to to make shellcheck ignore doc strings (SC2016)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#506]
1. Clone and enter this repo:
   ```sh
   git clone https://github.com/webinstall/webi-installers.git ./webi-installers/
   cd ./webi-installers/
   ```
2. Install [`shellcheck`](https://webinstall.dev/shellcheck) and [`shfmt`](https://webinstall.dev/shfmt):
   ```sh
   curl -sS https://webinstall.dev/shellcheck | sh
   curl -sS https://webinstall.dev/shfmt | sh
   ```
3. FOLLOW THE ON-SCREEN INSTRUCTIONS (from the installs)
4. Check to see which scripts have docs that look like commands
   ```sh
   shellcheck -s sh -i SC2016 */*.sh */*/*.sh
   ```
   Example:
   ```txt
   In pyenv/install.sh line 12:
           echo 'eval "$(pyenv init -)"' >> ~/.bashrc
                ^----------------------^ SC2016 (info): Expressions don't expand in single quotes, use double quotes for that.

   In pyenv/install.sh line 13:
           echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
                ^-- SC2016 (info): Expressions don't expand in single quotes, use double quotes for that.
   ```
5. Add `# shellcheck disable=2016` above any `echo` that's being used to output docs or literal commands rather than for variable expansion. For example:
   ```diff
   +        # shellcheck disable=2016
            echo 'eval "$(pyenv init -)"' >> ~/.bashrc
   +        # shellcheck disable=2016
            echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
   ```
   (probably all of those shellcheck complaints should be ignored)

**Comment by rishavnandi** [comment]
Hi, I will be taking this one up, giving this issue a shot. 👍🏻

**Comment by y0rune** [comment]
Hello!
As far I remember correctly you can add the string `# shellcheck disable=2016` at the beginning lines of the script or we would like only disable the specific lines @coolaj86?

**Comment by coolaj86** [comment]
@y0rune We only want to ignore the specified lines (there's not that many of them).

If we ignored the whole file then a future edit could allow an error without warning.

**Comment by y0rune** [comment]
All right good point @coolaj86 ;)
