### ISSUE TITLE
Why is webi.sh not redirect to information page about the package?

### ISSUE THREAD

**Issue by y0rune** [webinstall/webi-installers#513]
## What exactly did you do?
In the browser I wrote the new page https://webi.sh/rg and it does not redirect into a information page as should like https://webinstall.dev/rg/

## What went wrong?
The page should look like:
![image](https://user-images.githubusercontent.com/10187235/187271564-fd2b9ad6-ce10-4a2d-9baa-66b2fd5200df.png)

But looked:
![image](https://user-images.githubusercontent.com/10187235/187271374-6f29b9f0-a652-489e-aab0-2a5337aec3bc.png)

## Which OS did you try on?
- [X] Mac - Safari
- [X] Mac - Firefox
- [X] Mac - Chrome

**Comment by coolaj86** [comment]
This is the correct behavior for `https://webi.sh/<pkg>` and `https://webi.ms/<pkg>`.

`https://webinstall.dev/<pkg>` will continue to show all three forms (html, sh, ps1). It is generally considered a bad practice to do that sort of user-agent switching, but at the time it was cute, we had 3 different formats, and I didn't want to make the url longer by adding query params or paths.

Now you can type less, and be more exact.

However, I would like to add a link up at the top to direct users to the documentation page.

**Comment by y0rune** [comment]
Thank you for answer 👍

**Comment by coolaj86** [comment]
I think we could serve the scripts with `Content-Type: text/html` \
and have `# <meta http-equiv="refresh" content="0; URL='https://webinstall.dev/node/'" />`.

Thoughts?

cc/ @y0rune @ryanburnette

**Comment by y0rune** [comment]
Nice!
I think it is working as should ;) 
Good job @coolaj86!
