### ISSUE TITLE
`fzf` is not the latest version because the release URL has changed

### ISSUE THREAD

**Issue by NoahELE** [webinstall/webi-installers#514]
## What were you trying to install (or what else went wrong)?

`fzf`

## What exactly did you do?

```
$ webi fzf
```

## What went wrong?

The latest version on github is now `0.33.0`, and webi only installs `0.23.1`.

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
The author changed the releases URL. \
(See https://github.com/junegunn/fzf/issues/2173 and https://github.com/junegunn/fzf-bin)

@NoahELE This is a **super** easy fix. Would you care to PR?

`./fzf/releases.js`:

```diff
- var repo = 'fzf-bin'
+ var repo = 'fzf'
```

**Comment by NoahELE** [comment]
@coolaj86 I've created a PR.

**Comment by coolaj86** [comment]
Deployed.
