### ISSUE TITLE
[Bug] Installing `deno` fails on linux

### ISSUE THREAD

**Issue by jojobyte** [webinstall/webi-installers#522]
## What were you trying to install (or what else went wrong)?

deno

## What exactly did you do?

I ran both `webi deno` & `curl -sS https://webi.sh/deno | sh` to try to install deno.

## What went wrong?

I get the following error:

> Thanks for using webi to install 'deno' on 'Linux/x86_64'.
> 
> Error: no 'deno' release for 'linux' on 'amd64' as one of 'tar,exe,xz,git,dmg' by the tag 'stable'
>        'deno' is available for 'macos,windows,linux' on 'arm64,amd64' as one of 'zip,tar'
>        (check that the package name and version are correct)
> 
>        Double check at https://webinstall.dev/api/releases/deno@stable.tab

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [x] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
The error message is slightly incorrect due to the order or checking.

Most likely you've got a fresh install and you haven't yet installed `zip`, so you can't unzip, and you haven't installed `xz`, so you can't untar, even though `tar` is installed.

**Comment by coolaj86** [comment]
Yep: https://webinstall.dev/api/releases/deno.json?pretty=true

All of the packages are only available as zip, except for the source which is tar - which confuses the heuristics because tar is one of the available options... but actually an option that can be used.

**Comment by jojobyte** [comment]
> The error message is slightly incorrect due to the order of checking.
> 
> Most likely you've got a fresh install of Linux and you haven't yet installed `zip`, so you can't unzip, and you haven't installed `bz2` or `gz`, so you can't untar, even though `tar` is installed.

Ohhh, hey, look at that. `apt install zip` and it worked great!. I'll either make a PR here or create an issue with deno sometime soon. Thanks for the quick response!
