### ISSUE TITLE
question on Caddy installer

### ISSUE THREAD

**Issue by cekvenich2** [webinstall/webi-installers#528]
I *LOVE* webi. I'll send a separate email on that. 

When Caddy runs as a service, where should I place the Caddyfile? (ubuntu)

**Comment by ryanburnette** [comment]
This is a matter of personal preference. When I set up a web server I start by running [ssh-adduser](https://webinstall.dev/ssh-adduser/) which gives me the `app` user, then I keep my `Caddyfile` in the home directory for the `app` user. This makes making an ssh connection to the app user then a subsequent `vim Caddyfile` a quick way to get in and manage. After using [serviceman](https://webinstall.dev/serviceman) to add it as a service, restarts are `sudo systemctl restart caddy` and logs are `sudo journalctl -xef --unit caddy`. Hope this helps... again it's just one way of doing things and others may have another way that they prefer.
