### ISSUE TITLE
Request for xcaddy

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#531]
We need to get [xcaddy][1] in the mix.

[1]: https://github.com/caddyserver/xcaddy

**Comment by ryanburnette** [comment]
@coolaj86 Or maybe not. I'm not familiar with go, can you take a look at the [xcaddy][1] readme and tell me if just installing using the go command is preferable?

[1]: https://github.com/caddyserver/xcaddy

**Comment by cekvenich2** [comment]
xcaddy is a corner case and: there is command to install go and then you can make it.

**Comment by ryanburnette** [comment]
I agree. Close.
