### ISSUE TITLE
<!-- 🙌 Thanks for contributing to MDN Web Docs. Adding details below will help us to merge your PR faster. -->

### ISSUE THREAD

**Issue by Mimo3030** [webinstall/webi-installers#541]
### Description

This change normalizes the capitalization of the `title` and `slug` properties for entries in the Glossary to the most common pattern among those pages.

### Motivation

The `title`s and `slug`s of enties in the [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) have inconsistent capitalization. Most of them capitalize the first letter, and otherwise apply the same capitalization of the title to the slug (URL). It would be desirable to have a consistent capitalization standard for these properties.

### Additional details

I can understand the desire to keep URLs lowercase, or that to make titles use lowercase if they're words that aren't proper nouns. I would be happy to perform the corresponding alternative changes to the glossary pages if consistently applying one (or both) of these properties is prefered. 

Note: since this change will affect URLs, I wonder if there's a way to provide redirects from the previous URLs so that links won't be broken.

### Related issues and pull requests

_Originally posted by @waldyrious in https://github.com/mdn/content/pull/23297_

**Comment by coolaj86** [comment]
What huh?
