### ISSUE TITLE
[Website] Some `<code>` in FAQ rendered wrongly

### ISSUE THREAD

**Issue by YDX-2147483647** [webinstall/webi-installers#556]
Some `<code>` in [FAQ](https://webinstall.dev/faq/) are rendered wrongly. I guess spaces are missing in markdown?

You can search “`” in that page:

> without being \`root\` → without being `root`

> `webi` doesn’t need \`root\`, \`sudo\`, or Admin privileges → `webi` doesn’t need `root`, `sudo`, or Admin privileges

> \`webi\` uses the official releases API → `webi` uses the official releases API

---

Besides, is there a place to contribute to the website? I notice #435, #513, …

**Comment by coolaj86** [comment]
@YDX-2147483647 Thanks. That's a Markdown fail. I'll fix that.

**Comment by coolaj86** [comment]
Fixed!

```vim
:%s:`\([^`]*\)`:<code>\1</code>:gc
```
