### ISSUE TITLE
[Bug] Installation errors due to 500 on pathman installer

### ISSUE THREAD

**Issue by chrisRedwine** [webinstall/webi-installers#559]
## What were you trying to install (or what else went wrong)?

Trying to install `webi` (and other apps).

## What exactly did you do?

I ran `curl -sS https://webi.sh/ | sh` (same result for `curl -sS https://webi.sh/k9s | sh`).

## What went wrong?

It seems to have installed `webi`, but the post-installation message shows an error related to the `pathman` installer and returns with exit code 1:
```con
Thanks for using webi to install 'webi@stable' on 'Darwin/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers


'webi' installed to ~/.local/bin/webi

Usage:
    webi <package-name>[@version] ...

Example:
    webi node@lts prettier vim-essentials

curl: (22) The requested URL returned error: 500
error fetching 'https://webi.sh/api/installers/pathman.sh?formats=tar,exe,zip,xz,git,dmg,pkg'
```

Note that `https://webi.sh/api/installers/pathman.sh` does indeed return 500, whereas other installers appear to be fine. Also, note that this seems to happen for other installers (such as `k9s`) with the same error at the end.

## Which OS did you try on?

- [x] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
There's an issue connecting with the GitHub API to get list of releases.

Investigating now.

Should be back up shortly.

**Comment by coolaj86** [comment]
No sooner that I inspected it than did it resolve itself.

Due to the nature of the error, it didn't trigger any useful logs.

I've put some extra logging in place around the GitHub Releases API call on non-success responses.

**Comment by coolaj86** [comment]
Thank you very much for the report.

**Comment by chrisRedwine** [comment]
You bet - thanks for the quick response!

**Comment by AlejandroGallar** [comment]
Hello folks,

I'm having this exact issue when trying to install k9s:

~$ curl -sS https://webinstall.dev/k9s | bash

curl: (22) The requested URL returned error: 500 
error fetching 'https://webinstall.dev/api/installers/k9s@stable.sh?formats=tar,exe,zip,xz,git,dmg'

I have tried many different things, any suggestion?

Thanks!

**Comment by coolaj86** [comment]
@AlejandroGallar It's fixed now. I'm going to look into this more deeply again today. It's a strange bug that happening more and more frequently, and is very elusive in that it doesn't like to leave messages in the logs... despite the fact that I'm literally calling the logger when it happens, only happens in the middle of the night, and I can never reproduce.

**Comment by coolaj86** [comment]
Update: Fixed (for the... last? time) via #565
