### ISSUE TITLE
[Bug] Weak OS detection

### ISSUE THREAD

**Issue by YDX-2147483647** [webinstall/webi-installers#561]
## What went wrong?

My linux computer's name (or `hostname`) includes `mac`, and `https://webi.sh/api/` thinks it's macOS.

User-Agent:

```
curl Linux river-virtual-machine 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
                         👆 Here is the “mac”.
    (“river-virtual-machine” is my computer's name)
```

You can reproduce it on any platform: manually `curl -H …`, then `-machine` receives macOS, and `-mahine` receives `linux`.

> **Note**: The following is a detective story that might be off-topic. So skip if you want.

## What were you trying to install (or what else went wrong)?

I tried to install `lsd` first, but `pathman` seemed to be broken (`Exec format error`).

_Remark_: I never install `pathman` before — it was required by the script. However, I believe this won't get fixed even after #505 is completed.

Then I [uninstalled everything that installed with webi](https://webinstall.dev/faq/#uninstall-webi), and [`curl -sS https://webi.sh/pathman | sh`](https://webinstall.dev/pathman/). This time `pathman` was installed, but still broken:

```bash
$ pathman --help
… cannot execute binary file: exec format error
```

I modify those scripts and find what webi really downloads is `pathman-v0.5.2-macos-amd64.tar.gz`.

```bash
$ curl https://webi.sh/api/installers/pathman@stable.sh?formats=tar,exe,zip,xz,git,dmg -sS | rg -e 'WEBI_RELEASES=.+?os=[^&]+&'
WEBI_RELEASES='https://webi.sh/…?os=linux… ✔️

$ uname -a
Linux river-virtual-machine 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ curl https://webi.sh/api/installers/pathman@stable.sh?formats=tar,exe,zip,xz,git,dmg -sS -H "User-Agent: curl $(uname -a)" | rg -e 'WEBI_RELEASES=.+?os=[^&]+&'
WEBI_RELEASES='https://webi.sh/…?os=macos… ❌
```

## What exactly did you do?

`curl -sS https://webi.sh/pathman | sh` for a fresh install.

## Which OS did you try on?

- [ ] Mac
- [x] Windows (Host)
- [x] Linux (Guest)

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Thanks for the report.

Ugh... this is a pickle.

Actually... 💡 I just recently saw how Bun does their detection using `uname -mprs`. I didn't actually know you could combine the flags before. For some reason (probably because I had never seen it done any other way) I had assumed you specified one flag and got one output.

- `-m` for `machine platform`
- `-p` for `machine processor architecture` is non-standard, but I think `-v` includes that too
- `-r` for `operating system release level`
- `-s` for `operating system implementation`

**Comment by coolaj86** [comment]
Thanks again @YDX-2147483647 for the report. It's fixed via #562.

Drop your Đash Wallet address here (or DM me) and I'll send a tip / buy you lunch.

:)

P.S. You will still need to remove the `pathman` binary and let it download again. I do have fixing #505 on this month's To-Do list (it will be similar to [aliasman](https://github.com/BeyondCodeBootcamp/aliasman), which I did this week).

**Comment by YDX-2147483647** [comment]
Thanks. It's amazing that you fixed it only in hours.

(❤️ Leave the tip for yourself :-)

**Comment by coolaj86** [comment]
>  It's amazing that you fixed it only in hours.

I was just about to start a code stream (https://www.youtube.com/watch?v=cY3BLdh7kp4) when the message came in, and I had a little help from my friends - @y0rune, and a few others, who were able to quickly test and confirm the string outputs on a few platforms I didn't have on hand.

Some of the feature stuff takes a while for me to get around to, but bugfixes are a high priority for Webi.
