### ISSUE TITLE
Typo - About Section

### ISSUE THREAD

**Issue by HacDan** [webinstall/webi-installers#574]
In Ryan's blurb/bio whatever you want to call it, there's a double "them"

> I’m working on webi because I find tools like [pathman](https://git.rootprojects.org/root/pathman) and [serviceman](https://git.rootprojects.org/root/serviceman) incredibly valuable. I want the easiest possible way to install **them ~~them~~** as I set up new client machines, as well as to share them with others.

I couldn't find this in the repo, so I'm assuming it lives somewhere else, but I figured this would be the best place to post an issue for it. 

Offending URL: https://webinstall.dev/about/

![Screenshot 2023-02-25 at 2 14 51 PM](https://user-images.githubusercontent.com/155105/221375617-2bea6318-4180-4b17-ada9-d35e2a20ca27.jpg)

**Comment by coolaj86** [comment]
Thanks. Fixed and deployed.

(and I also used a little `Promise._parallel()` to fix a rate-limit issue on the build renderer that we're finally hitting now that we have so many installers -<https://github.com/GPTScript/AiScript/issues/9>)

**Comment by coolaj86** [comment]
And, yes, our brand assets are in a different repo.
