### ISSUE TITLE
Request for CMake

### ISSUE THREAD

**Issue by jcbhmr** [webinstall/webi-installers#579]

**Comment by coolaj86** [comment]
Looks like this could be done the same as any other installer: https://github.com/Kitware/CMake/releases/tag/v3.26.4

Anyone interested in taking this on, see https://github.com/webinstall/webi-installers/blob/main/.github/ISSUE_TEMPLATE/new_installer.md for instructions.

**Comment by brthngnsh** [comment]
Hi, I would like to take up this task to add CMake installer.

**Comment by brthngnsh** [comment]
Please review #625 to enable CMake Installer.

**Comment by coolaj86** [comment]
Closed via #625
