### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by marcpmichel** [webinstall/webi-installers#597]
## What were you trying to install (or what else went wrong)?

webi on Windows 11

## What exactly did you do?

curl.exe https://webi.ms/arc | powershell

## What went wrong?

error downloading pathman.exe

```
curl "https://rootprojects.org/pathman/dist/windows/amd64/pathman.exe"
curl: (7) Failed to connect to rootprojects.org port 443 after 2931 ms: Couldn't connect to server
```

the url is from :[install.ps1]( https://github.com/webinstall/webi-installers/blob/main/pathman/install.ps1)

**Comment by scott-morris** [comment]
It appears that all of https://rootprojects.org is denying connections. May need to find another source for this executable.

**Comment by coolaj86** [comment]
Looking into this now. That should have been git.rootprojects.org.

**Comment by coolaj86** [comment]
Fixed. @scott-morris Try now.

A few years ago the Linux installer was updated to use the git release URL, but the Windows installer was not. Despite that, the old release location remained up for all these years, until now.

My apologies to @marcpmichel and others who were having trouble with this earlier and I didn't see the report.
