### ISSUE TITLE
Can't install lsd on darwin arm64

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#617]
Right now you can't install lsd on darwin arm64 because it is missing from their releases.

They are going to be adding it to the builds in their next release.
https://github.com/lsd-rs/lsd/issues/844

For now...

```sh
webi rust
cargo install lsd
```

**Comment by coolaj86** [comment]
No change needed.

If you have Rosetta 2 this works, and if not, it will start working once they've completed their release process for ARM64.
