### ISSUE TITLE
[Bug] path not updated when installing webi on macos/arm64 fish

### ISSUE THREAD

**Issue by ryanburnette** [webinstall/webi-installers#618]
## What were you trying to install (or what else went wrong)?

Tried to install webi on a freshly loaded mac, the path wasn't updated so I had to run webi from the full path to install pathman, then use pathman to update my path. The only thing I had done was install and switch to fish.

## What exactly did you do?

```shell
curl https://webi.sh/webi | sh
```

## What went wrong?

path not updated

## Which OS did you try on?

macos ventura

- [x] Mac
- [ ] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

mbp amd64

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
I need a little more info on this.

Did you install fish _before_ or _after_ running the command?

This is the logic for detecting fish:
- https://github.com/webinstall/webi-installers/blob/main/_webi/template.sh#L359
- https://github.com/webinstall/webi-installers/blob/main/_webi/template.sh#L414

Can you think of any reason that would fail on your system?

**Comment by mathwhiz1212** [comment]
> I need a little more info on this.
> 
> * Did you install fish _before_ or _after_ running the command?
> * Is it in `~/.config/envman/PATH.env`?
> * Does `~/.config/envman/load.fish` exist?
> * Does `~/.config/fish/config.fish` exist?
> * Does `~/.config/fish/config.fish` contain a reference to `.config/envman/load.fish`?
> 
> This is the logic for detecting fish:
> 
> * https://github.com/webinstall/webi-installers/blob/main/_webi/template.sh#L359
> * https://github.com/webinstall/webi-installers/blob/main/_webi/template.sh#L414
> 
> Can you think of any reason that would fail on your system?

@ryanburnette

**Comment by coolaj86** [comment]
Closing this out unless we get further information.

I've done several new computer installs recently and several VM installs and I haven't reproduced this problem.
