### ISSUE TITLE
Syncthing Stopped Running Automatically

### ISSUE THREAD

**Issue by mathwhiz1212** [webinstall/webi-installers#635]
## What went wrong?

I installed Syncthing with Webi, it started automatically for probably over a year. Then a few days ago it stopped.

I can run `serviceman start syncthing` and it works fine, I just have to remember to do that or create an autostart script for it.

Is there a way to resolve this issue? Reinstalling Syncthing/Serviceman/Webi?

## Which OS did you try on?

- [ x] Mac

## What type of computer?

- [ x] Apple Silicon M1 Mac Mini

**Comment by coolaj86** [comment]
Take a look at the examples on <https://webinstall.dev/serviceman/>.

Typically `syncthing` is something you want to run as your user with your user's permissions. However, if you want it to run as a system daemon you'll need to use the `sudo env PATH=...` with `--system`.

**Comment by coolaj86** [comment]
Scratch that. You're on macOS.

Did you do a macOS upgrade recently?

It may have just become unregistered from launch services and a reinstall would fix it.

**Comment by coolaj86** [comment]
I'm going to close this out because I don't think it's specifically a Webi issue, but we can keep the thread going here and if it turns out to be related to Webi we can reopen.

**Comment by mathwhiz1212** [comment]
> Did you do a macOS upgrade recently?

Yep.

> It may have just become unregistered from launch services and a reinstall would fix it.

How would I manually re-register it under my user like webi does by default?

I'd prefer not to scrap my Syncthing settings in a reinstall because it's setup to sync all my devices.

**Comment by mathwhiz1212** [comment]
Though if it's the webi docs somewhere I can find it on my own.

**Comment by mathwhiz1212** [comment]
For the curious, I set the serviceman start command to run at boot.
