### ISSUE TITLE
problem with GitHub CLI installer

### ISSUE THREAD

**Issue by ezraakankwasa** [webinstall/webi-installers#640]
I keep getting this error no matter what I try on my ubuntu cli: curl: (6) Could not resolve host: webi.sh

**Comment by mathwhiz1212** [comment]
@ezraakankwasa Try setting your DNS to 1.1.1.1 and trying again.

**Comment by coolaj86** [comment]
It should be required to make any DNS changes long term, but as a temporary test, using CloudFlare (1.1.1.1) or Google (8.8.8.8) can make sense.

Is there anything special about your network that might cause `.sh` domains to be blocked?

If so, you can try `webinstall.dev`. It's the same server as `webi.sh`.

**Comment by coolaj86** [comment]
Going to close this out because I think it was a temporary issue.
