### ISSUE TITLE
[Bug] webi.sh down

### ISSUE THREAD

**Issue by primeinc** [webinstall/webi-installers#644]
## What were you trying to install (or what else went wrong)?

webi.sh does not resolve

## What exactly did you do?

`curl -sS https://webi.sh/ | sh`

## What went wrong?

`curl: (6) Could not resolve host: webi.sh`

## Which OS did you try on?

- [x ] Linux

Looks like its down everywhere [https://imgur.com/CIPLpKf](https://imgur.com/CIPLpKf)

**Comment by mathwhiz1212** [comment]
@primeinc It's working currently: https://www.isitdownrightnow.com/webi.sh.html

Does it work for you now.
