### ISSUE TITLE
[Bug] envman with default install duplicates existing path 

### ISSUE THREAD

**Issue by joebb97** [webinstall/webi-installers#653]
## What exactly did you do?
I ran the command from the project website `curl -sS https://webi.sh/ | sh`. This adds a directory `$HOME/.config/envman`. The install script adds a line to the shell's configuration file to source the contents in `envman` . These scripts at some point do something like `export PATH="/usr/local/bin:$PATH`

This duplicates the existing path on subsequent shell runs.

**Comment by joebb97** [comment]
I didn't describe this very well, I'll try to explain better when I get a chance.

**Comment by coolaj86** [comment]
Hey @joebb97,

Some distros add that to the PATH, others don't. However, it's extremely difficult to reliably detect that it is set correctly and actually working in the current environment - or that it's permanently set and not just in the temporary environment.

It's also difficult to get that working cross-platform, cross-shell.

The tradeoff is that sometimes, for some distros or environments, the PATH will be listed twice - which is better than NOT being listed.

This is similar to the "At least once problem"

I definitely agree that it would be a nicer aesthetic to have the PATH entry guaranteed to be **only once**, but it's more reliable for more people to have it guaranteed to be in there **at least once**.

My core concern is that "It Just Works™".

That all said, if you've got ideas for how to change the detection to be reliable in diverse environments, I really would love to get that implemented.

**Comment by coolaj86** [comment]
I'm closing this out since I don't believe there's anything to do, but please continue to comment with ideas or reopen if you figure out what the action items should be. :)
