### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#661]
# How to Help?

- PRs for Installers
- Chores (cleanup, consistency, **documentation**, etc)
- See what's **Up for Grabs**
- Help us hit 1.1k stars (#287)

## 1. Add an installer

See the **list of things people want**:
- <https://github.com/webinstall/webi-installer-requests/issues>

Watch the How To video:
- [![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

Check out The Matrix, the examples, and a tool with a similar package to the one being installed:
- [Categories of Installer ("The Matrix")](https://github.com/webinstall/webi-installers/issues/412)
- Generic Example: https://github.com/webinstall/webi-installers/tree/main/_example
- GoReleaser-style Example: [_examples/built-with-goreleaser](https://github.com/webinstall/webi-installers/tree/main/_examples/built-with-goreleaser)
- Bare Bin w/ xz Example: [_examples/compressed-with-xz](https://github.com/webinstall/webi-installers/tree/main/_examples/compressed-with-xz)

## 2. Do some Chores

There's a number of clean-up tasks that need to be done across the many of the installers:
- PR the project with Webi instructions (TODO: needs link to example PR)
- Add or cleanup the `### Files` section of each repo: https://github.com/webinstall/webi-installers/issues/660
- Update Documentation https://github.com/webinstall/webi-installers/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation

## 3. See what's Easy and what's **Up for Grabs**

- [good first issue](https://github.com/webinstall/webi-installers/issues?q=is%3Aopen+is%3Aissue+label%3A"good+first+issue")
- [first-timers-only](https://github.com/webinstall/webi-installers/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only)
- [up-for-grabs](https://github.com/webinstall/webi-installers/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs)

**Comment by y0rune** [comment]
I think the good idea is to test it at Docker Instance or at local system.
What do you think @coolaj86 and @jojobyte ;) ?

**Comment by coolaj86** [comment]
@y0rune Yes. Give us more details. What do you think is the best route to accomplish this?

**Comment by coolaj86** [comment]
Closing since this is not an action item, but a sticky documentation / discussion issue.

**Comment by Abdozine405** [comment]
Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is Msys/MINGW32_NT-6.2/i686 with libc & curl)
sh: line 332: HOME: unbound variable

What do I do in this situation ?
