### ISSUE TITLE
Reserve red for error

### ISSUE THREAD

**Issue by virzak** [webinstall/webi-installers#668]
Is it possible to replace red or configure colors? Appreciate the messaging, and the offering, but installers aren't supposed to make people freak out.

![image](https://github.com/webinstall/webi-installer-requests/assets/6209775/622f5eba-82f7-4ad4-8755-78957cdd2c99)

**Comment by coolaj86** [comment]
That's reasonable. I definitely want "TO FINISH" to stand out, but I suppose it's reasonable to choose a different color.

What color would you suggest?

**Comment by virzak** [comment]
I'd use an ⚠️ prefix with any color (yellow?), maybe even white. But I'm not a designer.

**Comment by coolaj86** [comment]
I think yellow could be a good choice. I'm hesitant to try ⚠️. I don't think that works in the default Windows terminal.

> But I'm not a designer.

Don't cut yourself short. Reserving red for errors is definitely a UX design thing.

**Comment by thegreatestgiant** [comment]
So every single line of red to yellow or orange?

**Comment by coolaj86** [comment]
Here's what it looks like in very generic, ugly themes now:

<img width="1002" alt="Screenshot 2023-10-17 at 12 58 51 PM" src="https://github.com/webinstall/webi-installers/assets/122831/76ead65c-6910-4ce5-8944-5fc748d37f7e">

<img width="1082" alt="Screenshot 2023-10-17 at 1 00 14 PM" src="https://github.com/webinstall/webi-installers/assets/122831/b6b39d1f-85b9-45ef-a3ad-197e0939b8b6">

I ditched blue entirely because it's almost always the least visible.

Closed via #672

**Comment by coolaj86** [comment]
Here's what it looks like in other popular themes, such as Tomorrow Night, Dracula, Ubuntu, Tango, and Solarized:

<img width="1162" alt="Screenshot 2023-10-17 at 1 04 48 PM" src="https://github.com/webinstall/webi-installers/assets/122831/b662f629-43e0-423f-a079-859f208e710f">
<img width="1162" alt="Screenshot 2023-10-17 at 1 04 41 PM" src="https://github.com/webinstall/webi-installers/assets/122831/14434f7d-6832-4357-8a2a-882bc7e72f2a">
<img width="1162" alt="Screenshot 2023-10-17 at 1 04 36 PM" src="https://github.com/webinstall/webi-installers/assets/122831/a5b73c09-e86c-4ac9-8dce-a37df6a0fd69">
<img width="1162" alt="Screenshot 2023-10-17 at 1 04 30 PM" src="https://github.com/webinstall/webi-installers/assets/122831/e653602e-96d0-4fea-bd96-54d68f8665fd">
<img width="1162" alt="Screenshot 2023-10-17 at 1 04 24 PM" src="https://github.com/webinstall/webi-installers/assets/122831/b1900c4c-e048-4610-8cc1-da28e3a9ca0c">
<img width="1162" alt="Screenshot 2023-10-17 at 1 04 15 PM" src="https://github.com/webinstall/webi-installers/assets/122831/70046112-e072-4156-ade6-c098927d48f2">
<img width="1162" alt="Screenshot 2023-10-17 at 1 04 07 PM" src="https://github.com/webinstall/webi-installers/assets/122831/0f79db90-d3a2-42d8-8862-241b048fd28c">
<img width="1162" alt="Screenshot 2023-10-17 at 1 03 31 PM" src="https://github.com/webinstall/webi-installers/assets/122831/fc034def-fbca-4084-99e1-348bb4b54f81">
<img width="1162" alt="Screenshot 2023-10-17 at 1 03 19 PM" src="https://github.com/webinstall/webi-installers/assets/122831/e2b865a1-eb96-4418-af4e-ce9f65476e5a">
<img width="1162" alt="Screenshot 2023-10-17 at 1 03 12 PM" src="https://github.com/webinstall/webi-installers/assets/122831/734e965e-5adb-4c01-a385-8c243ead9eb0">
<img width="1162" alt="Screenshot 2023-10-17 at 1 02 59 PM" src="https://github.com/webinstall/webi-installers/assets/122831/f2d42f52-c418-4801-bb1b-f882110368fc">
<img width="1162" alt="Screenshot 2023-10-17 at 1 02 47 PM" src="https://github.com/webinstall/webi-installers/assets/122831/c50c952b-e52b-4179-a743-b2a9574192e3">
<img width="1162" alt="Screenshot 2023-10-17 at 1 02 33 PM" src="https://github.com/webinstall/webi-installers/assets/122831/ba77ab03-7b57-45de-af95-4cfe65001e29">
<img width="1162" alt="Screenshot 2023-10-17 at 1 02 08 PM" src="https://github.com/webinstall/webi-installers/assets/122831/7eadd103-341d-48f3-9acf-84159a74e92d">

**Comment by coolaj86** [comment]
Thanks again @virzak for the feedback. :)
