### ISSUE TITLE
Add msvc update to `bat` installer (super easy)

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#675]
We need to update `bat` to install MSVC the same as `dotenv-linter`, and update the README:

- `dotenv-linter` updates
  - https://github.com/webinstall/webi-installers/pull/674/files
- `bat`'s `install.ps1`
  -  https://github.com/webinstall/webi-installers/blob/main/bat/install.ps1
- `bat`'s `README.md`
  - https://github.com/webinstall/webi-installers/blob/main/bat/README.md

This section should be added above the `# Fetch archive` section:

```pwsh
# Fetch MSVC Runtime
echo "Checking for MSVC Runtime..."
IF (-not (Test-Path "\Windows\System32\vcruntime140.dll"))
{
    & "$Env:USERPROFILE\.local\bin\webi-pwsh.ps1" vcruntime
}
```

The README should be updated as well to include similar language to `dotenv-linter`:

~~~mkdn
**Windows Users**

```text
\Windows\System32\vcruntime140.dll
```

This will also attempt to install the
[Microsoft Visual C++ Redistributable](/vcruntime) via `webi vcruntime`. If it
fails and you get the error _`vcruntime140.dll` was not found_, you'll need to
[install it manually](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170).
~~~

**Comment by PUNEET-EMM** [comment]
May i work on this...?

**Comment by coolaj86** [comment]
@PUNEET-EMM Looks like someone already took this, but there are equally easy ones if you check out #660, there's several dozen to choose from.
