### ISSUE TITLE
add bash, zsh, fish completions to `webi`

### ISSUE THREAD

**Issue by Lockszmith-GH** [webinstall/webi-installers#698]
Adding bash-competion to the webi cli tool would be a great addition and quality-of life improvement.

I understand it's probably a non-trivial impelmentation, but having a package name auto-complete would go along way to promote the installation of the cli tool.

**Comment by coolaj86** [comment]
How about just a `webi list` or `Webi search`?

I'm all for command completion, but:
1. I've never done it
2. That would require a regularly updated local cache

I'd happily accept a PRs that generate Bash, ZSH, and Fish completions.

Could you do any of that?

**Comment by coolaj86** [comment]
Oooh! I happened across how `pyenv` does completions whilst working on #702, and I LOVE IT!

- command generates its on completions on-the-fly
- can fetch from the web while generating
- works across all shells at once, give that the outputs are correct

## Examples

- `~/.pyenv/completions/pyenv.bash`
- `~/.pyenv/completions/pyenv.fish`
- `~/.pyenv/completions/pyenv.zsh`

### `~/.pyenv/completions/pyenv.bash`:

```sh
function __fish_pyenv_needs_command
  set cmd (commandline -opc)
  if [ (count $cmd) -eq 1 -a $cmd[1] = 'pyenv' ]
    return 0
  end
  return 1
end

function __fish_pyenv_using_command
  set cmd (commandline -opc)
  if [ (count $cmd) -gt 1 ]
    if [ $argv[1] = $cmd[2] ]
      return 0
    end
  end
  return 1
end

complete -f -c pyenv -n '__fish_pyenv_needs_command' -a '(pyenv commands)'
for cmd in (pyenv commands)
  complete -f -c pyenv -n "__fish_pyenv_using_command $cmd" -a \
    "(pyenv completions (commandline -opc)[2..-1])"
end
aj@biggoron ~> cat ~/.pyenv/completions/pyenv.bash
_pyenv() {
  COMPREPLY=()
  local word="${COMP_WORDS[COMP_CWORD]}"

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(pyenv commands)" -- "$word") )
  else
    local words=("${COMP_WORDS[@]}")
    unset words[0]
    unset words[$COMP_CWORD]
    local completions=$(pyenv completions "${words[@]}")
    COMPREPLY=( $(compgen -W "$completions" -- "$word") )
  fi
}

complete -F _pyenv pyenv
```

### `~/.pyenv/completions/pyenv.fish`

```fish
function __fish_pyenv_needs_command
  set cmd (commandline -opc)
  if [ (count $cmd) -eq 1 -a $cmd[1] = 'pyenv' ]
    return 0
  end
  return 1
end

function __fish_pyenv_using_command
  set cmd (commandline -opc)
  if [ (count $cmd) -gt 1 ]
    if [ $argv[1] = $cmd[2] ]
      return 0
    end
  end
  return 1
end

complete -f -c pyenv -n '__fish_pyenv_needs_command' -a '(pyenv commands)'
for cmd in (pyenv commands)
  complete -f -c pyenv -n "__fish_pyenv_using_command $cmd" -a \
    "(pyenv completions (commandline -opc)[2..-1])"
end
```

### `~/.pyenv/completions/pyenv.zsh`:

```sh
if [[ ! -o interactive ]]; then
    return
fi

compctl -K _pyenv pyenv

_pyenv() {
  local words completions
  read -cA words

  if [ "${#words}" -eq 2 ]; then
    completions="$(pyenv commands)"
  else
    completions="$(pyenv completions ${words[2,-2]})"
  fi

  reply=(${(ps:\n:)completions})
}
```

**Comment by Lockszmith-GH** [comment]
I'm willing to try and tackle this, just not sure about bandwidth right now. If I find myself forking the project to try this, I'll update here.

**Comment by RubenRam** [comment]
I have experience with bash completions and python and could look into this @coolaj86

**Comment by coolaj86** [comment]
@RubenRam cool. I think adapting the scripts above will be the quickest path.

There are two PRs that need to go in before that goes in:
- [ ] https://github.com/webinstall/webi-installers/pull/710 (not deployed yet)
- [ ] https://github.com/webinstall/webi-installers/pull/706 (needs reword and review)

However, you can start working on it in a local copy of `webi` (as in copy `~/.local/bin/webi` to `~/bin/` and modify your self-managed version) and we can apply that once those make it through.

**Comment by coolaj86** [comment]
Closing the issue for this since it's in PR and on track to be accepted and pulled in via #742.
