### ISSUE TITLE
👷‍♂️ Progress Tracker / Roadmap 🚧

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#699]
# Actively in Queue

- [ ] #696 
- [ ] #697 
- [ ] #695 
- [ ] #648 
- [ ] #663 
- [ ] #662 
- [ ] #664 
- [ ] #669 

Also
- update homepage with new installers

**Comment by coolaj86** [comment]
Closing as sticky.

**Comment by ajaxStardust** [comment]
Pls delete as appropriate, or move to desired. Just wanted to say... 
Indeed, it is the “…without opening a GUI to Alt-Click "Run as Administrator"…” is the reason a person would google-it for "Open elevated windows command prompt"

It's comical to me that there are actual tutorials for the task which demonstrate how to access the "Run-as admin". It's like, who cares? Do you really think I'd know what it means to use an "elevated" prompt, if I didn't realize basic O/S utilization 

Anyway...
Thanks man! 
This is awesome! I've not known of webi-installers prior to finding your thread on stackoverkill about the elevanted prompt/ powershell script

Looking forward to further investigation! 
:)

Cheers and best regards!
