### ISSUE TITLE
(super easy) add `--workdir` flag to `brew` updater

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#700]
# Solution

We should explicitly set `--workdir ~/.local/opt/brew/`.

See:

https://github.com/webinstall/webi-installers/blob/4b8f62a1b805e588700d029ab44ddb530045d849/brew/brew-update-service-install#L9-L11

# Problem

```sh
brew-update-service-install
```

```text
OPTIONS: Making some assumptions...

	# Because this is your current working directory
	  --workdir /Users/aj/.local/opt/brew
````

**Comment by Virtual4087** [comment]
I would like to work on this

**Comment by coolaj86** [comment]
Do it!
