### ISSUE TITLE
[Bug] zig `master` should be tagged by date, otherwise it won't update

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#725]
'nuff said

**Comment by coolaj86** [comment]
Also, we need ZLS:

https://github.com/zigtools/zls

and zig.vim

**Comment by coolaj86** [comment]
This was fixed in https://github.com/webinstall/webi-installers/pull/757/commits/e05551cb069890cdf0d171a99526c0f5dd1004b0

**Comment by danawoodman** [comment]
@coolaj86 when installing Zig, I do not see ZLS installed as well and can't find the package in the list
