### ISSUE TITLE
Powershell doesn't have a RC for Windows

### ISSUE THREAD

**Issue by HacDan** [webinstall/webi-installers#733]
## What were you trying to install (or what else went wrong)?

Install Powershell on Windows

## What exactly did you do?

`webi powershell`

## What went wrong?

No release candidate

## Which OS did you try on?

- [ ] Mac
- [X] Windows (arm64, but doubt this was the issue)
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X] Laptop or Desktop (ARM64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by HacDan** [comment]
Easy - _Powershell 5_ ships with Windows. If you want a newer version of Powershell, for instance `Powershell Core 7.xx`, you have to go through a manual install process from Microsoft or through the Microsoft App Store. I'm not interested in signing into a Microsoft account for access and manual installs aren't exactly fun

**Comment by coolaj86** [comment]
#739
