### ISSUE TITLE
[Bug] Go installer failing

### ISSUE THREAD

**Issue by kdien** [webinstall/webi-installers#792]
## What were you trying to install (or what else went wrong)?

Go. Getting a different error after PR #791 got deployed.

## What exactly did you do?

Ran `webi go`. Other tools installed successfully (`fzf`, `bat`, etc.)

## What went wrong?

```sh
$ webi go
curl: (22) The requested URL returned error: 500
error fetching 'https://webinstall.dev/api/installers/go.sh?formats=tar,exe,zip,xz,git,dmg'
```

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Hey @kdien I just saw this probably at the same time you did and just fixed it... again.

The fix was only half-deployed, so it worked on the first request, but failed on the next.

My apologies.

**Comment by kdien** [comment]
@coolaj86 no worries at all. I understand regression all too well :smiley: 
I can confirm it just worked now for me. Thanks for the prompt response and the awesome work overall! I just recently discovered webi and am definitely a big fan.
