### ISSUE TITLE
[Bug:Docs] Copy button broken in Firefox

### ISSUE THREAD

**Issue by danawoodman** [webinstall/webi-installers#818]
## What were you trying to install (or what else went wrong)?

trying to copy the install code for a library

## What exactly did you do?

hit the copy button on the zig install on this page: https://webinstall.dev/zig/

## What went wrong?

nothing happened, copy failed, console produced this error:
![Screenshot 2024-02-28 at 11 17 20 AM](https://github.com/webinstall/webi-installers/assets/157695/3c018dbf-873a-48ee-91e3-a1b923b2c1a0)

## Which OS did you try on?

macOS 14.3.1, Firefox 123.0 

- [x] Mac
- [x] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by HacDan** [comment]
Can confirm happens on Firefox in PopOS (Ubuntu Derivative) as well.

Also noticed (although should probably be a separate issue) that OS detection isn't functioning in Firefox on PopOS. Just something of note while I was confirming this bug. I'll test Firefox on MacOS tonight.

**Comment by y0rune** [comment]
I confirm that error on Firefox at Mac (123.01), Windows 11, Linux :c

**Comment by coolaj86** [comment]
```js

**Comment by coolaj86** [comment]
I just did this for something else. I believe this function should work in Firefox:

```js
function copyUrlToClipboard(text) {
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(text).then(() => {
      console.log('URL copied to clipboard.');
    }).catch((err) => {
      console.error('Failed to copy the URL: ', err);
    });
    return;
  }

    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed'; // avoid scrolling to bottom
    textArea.style.opacity = '0'; // hidden
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    
    try {
      document.execCommand('copy');
      console.log('URL copied to clipboard.');
    } catch (err) {
      console.error('Failed to copy the URL: ', err);
    }
    
    document.body.removeChild(textArea);
}

copyUrlToClipboard(text);
```

It's used here: https://x5c.bnna.net/

**Comment by coolaj86** [comment]
Thank heavens as of June 2024, the ability to "Copy" in a browser has finally landed as "Baseline" support for Evergreen browsers: <https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write>

Who could have imagined that we'd ever see the day!?

Anyway, I updated the site and tested in Chrome, Firefox, and Safari. I can't believe it, but it works!
