### ISSUE TITLE
[Bug] k9s fails to update/install to latest version on Win 11

### ISSUE THREAD

**Issue by michaelgracious** [webinstall/webi-installers#831]
## What were you trying to install (or what else went wrong)?

Trying to install latest version of `k9s`

## What exactly did you do?

```
PS C:\Users\thul> webi k9s@latest

Welcome to Webi! - Instant Installs, Easy to Remember URLs
(PowerShell+curl Windows/10+ AMD64 msvc)


Installing k9s@latest
    Fetching install script ...
    Updating C:\Users\thul\.local\tmp\k9s@latest.install.ps1
    Downloading from
      https://webinstall.dev/api/installers/k9s@latest.ps1
        ?formats=zip,exe,tar,git&libc=msvc
      Saved C:\Users\thul\.local\tmp\k9s@latest.install.ps1
Installing k9s
Unpacking C:\Users\thul\Downloads\webi\k9s_Windows_amd64.zip
Install Location: C:\Users\thul\.local\opt\k9s-v0.32.4\bin\k9s.exe
Copying into 'C:\Users\thul\.local\bin\k9s.exe' from 'C:\Users\thul\.local\opt\k9s-v0.32.4\bin\k9s.exe'

Checking for updates to Webi ...
    Updating C:\Users\thul\.local\bin\webi-pwsh.ps1
    Downloading from
      https://webinstall.dev/packages/webi/webi-pwsh.ps1
      Saved C:\Users\thul\.local\bin\webi-pwsh.ps1

***********************************
*      IMPORTANT -- READ ME       *
*  (run the PATH commands below)  *
***********************************


Copy, paste, and run the appropriate commands to update your PATH:

cmd.exe:
    (close and reopen the terminal)

PowerShell:
    $UserPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $MachinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $Env:Path = "${UserPath};${MachinePath}"
    (or close and reopen the terminal)

PS C:\Users\thul>
```

## What went wrong?

It says its downloading and installing 0.32.4, but in reality when i start `k9s` i get 0.28.2 even after removing the k9s.exe from the bin directory. I have removed it, tried to run k9s, got an error that it didn't exist. Good, reinstalled it and expecting 0.32.4, but got 0.28.2 instead

Note, this is using cmd.exe cause powershell refuses to install anything for me (different bug posted)

## Which OS did you try on?

- [ ] Mac
- [X] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [X] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
Same as #832.

The latest Windows 11 PowerShell has a new security policy which blocks users from running unsigned scripts by default.

Investigating...

**Comment by coolaj86** [comment]
The current workaround is this:

## Use PowerShell Classic or cmd.exe

## Do NOT use PowerShell Core

I'm investigating how to support PowerShell Core and PowerShell Classic at the same time, but it's not looking good.
