### ISSUE TITLE
[Bug] Trying to install Git

### ISSUE THREAD

**Issue by 3f6a** [webinstall/webi-installers#833]
## What were you trying to install (or what else went wrong)?

git

## What exactly did you do?

```
curl -sS https://webi.sh/git | sh
```

## What went wrong?

I get a message saying:

```
'git' already installed
```

But yeah, I know it's already installed, it's just a very old version. I wanted `webi` to install a newer version for me so that I could use it.

So the point of this ticket is: Can we get `webi` to install the new version of `git`, taking precedence over the old one installed by default on the system?

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

More pspecifically, Ubuntu 20.04.6.

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

**Comment by coolaj86** [comment]
`git` doesn't have standalone releases for each platform.

Generally speaking we don't offer 3rd party builds. If the author doesn't provide the build, it's out of our hands.

I'm going to close this out. However, if you know a good way for us to get official builds of git for Linux, please reopen. I'd love to have it if the authors will make it available.

**Comment by coolaj86** [comment]
I just checked and they still don't offer builds for Mac or Linux:
https://git-scm.com/download/linux

Only Windows has official builds.

**Comment by HellAsfgh** [comment]
STOPSent from my iPhoneOn May 3, 2024, at 3:42 PM, AJ ONeal ***@***.***> wrote:﻿
Closed #833 as completed.

**Comment by coolaj86** [comment]
Building from C source is a bespoke process for every project. There is no uniform set of tools or processes.

Your best option would be to install brew via webi (so that it's installed conflict-free in your user directory) and the  brew install git.

brew works on Linux too these days.

I would consider breaking the "official 1st party builds only" rule for git since there are no official builds, but that would be a git mirror with releases.

I don't think I would ever want Webi to build C-family projects from source - it's just too complicated and requires too much maintenance and troubleshooting.

**Comment by coolaj86** [comment]
I really like the idea, but due to the reality of supply-chain vulnerabilities from rogue sleeper agents (npm, `xz`, etc), I wouldn't use those binaries.

Perhaps I could find their scripts and run them myself.

I would probably host the releases on github.com/webinstall/git-mirror or some such.

**Comment by coolaj86** [comment]
If you would get me a simple set of steps for how to do cross-platform builds, I'll put up a mirror and host them.

For example:

```
webi julia
source ~/.config/envman/PATH.env

git clone https://github.com/JuliaPackaging/Yggdrasil.git
pushd ./Yggdrasil/
julia --do-stuff --cross-platform --build=git

# see releases
ls ./builds/git/git-v2.4.4-*
```

Or better yet, extracting and transforming the bash script here to work on macOS to cross-compile with llvm:
- https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/Git/build_tarballs.jl
(I only peeked at it, that may be very simple)
