### ISSUE TITLE
Simple refactor: find-and-replace `whoami` with `id -u -n` in scripts

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#854]
`whoami` is generally available on all Unix-y systems, but `id -u -n` is the POSIX standard with guaranteed behavior.

This is literally as simple as doing a find-and-replace across the repo (such as with [`sd`](https://webinstall.dev/sd), or any code editor tool).

Finding the files with `whoami`:

```sh
git clone https://github.com/webinstall/webi-installers ./webi-installers
pushd webi-installers/
rg 'whoami' || grep -r 'whoami' .
```

For reference: https://pubs.opengroup.org/onlinepubs/009695399/utilities/id.html

**Comment by shuchitpant** [comment]
Hi AJ,

I've raised a PR (#915 ), that addresses this issue, kindly go through this and let me know if there are any changes.

**Comment by coolaj86** [comment]
Thank you!
