### ISSUE TITLE
Instructions to `source ~/.config/envman/PATH.env` are not prominent enough

### ISSUE THREAD

**Issue by Danjoe4** [webinstall/webi-installers#860]
## What were you trying to install (or what else went wrong)?
jq

## What exactly did you do?

`curl -sS https://webi.sh/jq | sh`

## What went wrong?

jq is not added to path 

## Which OS did you try on?

- [ ] Mac
- [ ] Windows
- [x] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

## more info ##

system is GNU/Linux/x86_64 with libc & curl+wget

when running the command again:
```>>> Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is GNU/Linux/x86_64 with libc & curl+wget)

Bootstrapping Webi
    Found ~/.local/bin/webi
    Running ~/.local/bin/webi jq@stable

Installing jq ...
    Found  ~/.local/bin
    'jq v1.7.1' already installed:
    ~/.local/bin/jq => ~/.local/opt/jq-v1.7.1/bin/jq
```

**Comment by coolaj86** [comment]
Hey @Danjoe4,

During the first install you would have been instructed to `source ~/.config/envman/PATH.env` or to close and reopen your terminal (or, in the case of zsh, it must be sourced because zsh has shared login sessions).

I do have planned to add this to the webpage as well.

**Comment by coolaj86** [comment]
This is now live on the webpage too.

<img width="673" alt="Screenshot 2024-12-18 at 12 47 00 AM" src="https://github.com/user-attachments/assets/47aaee0f-a133-4525-bd68-311617d0587a" />
