### ISSUE TITLE
[Bug] mkdir: Permission Denied

### ISSUE THREAD

**Issue by deltaepsilon** [webinstall/webi-installers#861]
I'm installing my first Webi package.

## What exactly did you do?

I ran `curl -sS https://webi.sh/golang | sh` on a new Mac.

## What went wrong?

```
➜  ~ curl -sS https://webi.sh/golang | sh


>>> Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is Darwin/arm64 with libc & curl)

Bootstrapping Webi
    Downloading https://webi.sh/packages/webi/webi.sh
        to ~/.local/bin/webi
mkdir: /Users/chrisesplin/.local/bin: Permission denied
```

I ran `chown chrisesplin:staff .local` to solve the permissions issue. Not a big deal... but maybe prompt the user on how to fix permissions when using Webi for the first time.

## Which OS did you try on?

- [x] Mac
- [ ] Windows
- [ ] Linux

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

MacBook Air M3, 8gb, with a migrated profile from my last Mac.

**Comment by coolaj86** [comment]
We communicated over Discord and it turned out to be a permission issue to do a problem with migration files from your old computer to your new computer.

**Comment by coolaj86** [comment]
I did some testing to see if this is something that Webi could reasonable handle.

I was hopeful that since the parent folder is owned by the correct user, that the perms on the child could be updated. However, that's not the case:

```sh
sudo mkdir -p ~/.test-local/opt/
sudo mkdir -p ~/.test-local/bin/
ls -lAhFd ~/.test-local ~/.test-local/*
```

```text
drwxr-xr-x root staff 128 B Mon Jul 15 18:17:23 2024 /Users/aj/.test-local/
drwxr-xr-x root staff  64 B Mon Jul 15 18:17:23 2024 /Users/aj/.test-local/bin/
drwxr-xr-x root staff  64 B Mon Jul 15 18:17:23 2024 /Users/aj/.test-local/opt/
```

```sh
chown -R "$(id -u -n)":"$(id -g -n)" ~/.test-local
```

```text
chown: /Users/aj/.test-local/bin: Operation not permitted
chown: /Users/aj/.test-local/opt: Operation not permitted
chown: /Users/aj/.test-local: Operation not permitted
```

So I'm going to close this out as something that isn't reasonable to account for because there are too few people with the problem and solving it either requires `sudo`, or a bunch of checks and additional prompts.
