### ISSUE TITLE
remove go guru

### ISSUE THREAD

**Issue by skovranek** [webinstall/webi-installers#882]
http://golang.org/s/using-guru

via the above link, it says:
> [Update: cmd/guru was [deleted](https://github.com/golang/go/issues/65880) in March 2024. It has long been superseded by [gopls](https://github.com/golang/tools/tree/master/gopls), a language (LSP) server for Go that works with a wide range of editors.]

Issue deleting it: https://github.com/golang/go/issues/65880

**Comment by coolaj86** [comment]
@skovranek Would you like to open a PR for this?

It should be as easy as removing or replacing these lines:

https://github.com/webinstall/webi-installers/blob/main/go-essentials/install.sh#L47-L49

https://github.com/webinstall/webi-installers/blob/main/go-essentials/install.ps1#L19-L22

**Comment by coolaj86** [comment]
completed in #892
