### ISSUE TITLE
problem with Hugo (Standard 

### ISSUE THREAD

**Issue by wathika-eng** [webinstall/webi-installers#886]
`Error: error building site: TOCSS: failed to transform "/ananke/css/main.css" (text/css). Check your Hugo installation; you need the extended version to build SCSS/SASS with transpiler set to 'libsass'.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information`

**Comment by coolaj86** [comment]
You'll need to use the other Hugo build:
https://webinstall.dev/hugo-extended/
