### ISSUE TITLE
problem with vim-gui installer

### ISSUE THREAD

**Issue by benjifriedman** [webinstall/webi-installers#933]
>>> Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is Darwin/arm64 with libc & curl)

Bootstrapping Webi
    Found ~/.local/bin/webi
    Running ~/.local/bin/webi vim-mouse@stable

curl: (56) The requested URL returned error: 500
error fetching 'https://webi.sh/api/installers/vim-mouse@stable.sh?formats=tar,exe,zip,xz,git,dmg,pkg'

**Comment by benjifriedman** [comment]
^^^ While trying to install https://webinstall.dev/vim-mouse/

**Comment by coolaj86** [comment]
Fixed via https://github.com/webinstall/webi-installers/pull/934.

This was deployed as a hotfix, and will officially go into `main` after the PR is reviewed.

Thanks for the report.

**Comment by coolaj86** [comment]
Out of curiosity: How did you come across `vim-mouse`?
It was renamed to `vim-gui` almost 4 years ago, so I'm surprised to see someone coming across the old alias.

**Comment by benjifriedman** [comment]
@coolaj86 oh interesting. It was from https://webinstall.dev/vim-mouse/

**Comment by benjifriedman** [comment]
Thank you for the fix as well!

**Comment by coolaj86** [comment]
@benjifriedman I know that's the page on the site, but how did you find it? Did it show up in a search or did you get the link from Stackoverflow, etc?

And you're welcome.

**Comment by benjifriedman** [comment]
@coolaj86 I think it was on the homepage, but it looks like it's been removed. @coolaj86 would know
